### ISSUE TITLE
registerModule with option { preserveState: true } not working

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [vuejs/vuex#1130]
### Version
3.0.1

### Reproduction link
[https://github.com/Serhiy-Nazarov/demo-error-with-vuex-register-module/blob/master/src/store/index.js](https://github.com/Serhiy-Nazarov/demo-error-with-vuex-register-module/blob/master/src/store/index.js)

### Steps to reproduce
git clone git@github.com:Serhiy-Nazarov/demo-error-with-vuex-register-module.git
yarn install
yarn dev

After this, open a console in the browser an look to messages.

### What is expected?
two modules will be registered

### What is actually happening?
Only first module (with preserveState: false) is registered

**Comment by LinusBorg** [comment]
You are misunderstanding what `preserveState` does, and what it's for:

When you set `preserveState: true`, the module *is* registered - actions, mutations and getters are added to the store. but the state is skipped, because it's assumed that your store state already contains state for that module (usually from from using SSR to render the app from the server) and you don't want to overwrite it - you want to preserve it.

We *could* add a check to see if that state is already there, and if it's not, add it anyway - but that's something that you can do yourself pretty easily:

```javascript
preserveState: !!store.state.test2
```

**Comment by phil294** [comment]
@LinusBorg why do the [docs on store code splitting](https://ssr.vuejs.org/guide/data.html#store-code-splitting) suggest that `serverPrefetch` should register with `{ preserveState: true }` then? On the server, there is no state yet, and as such, this fails.

In the docs example, it's `serverPrefetch ==> this.registerFoo() ==> this.$store.registerModule('foo', fooStoreModule, { preserveState: true })`. It doesnt make sense that both client + server share the same `registerFoo()` function
