### ISSUE TITLE
Document why getters that return functions belong into computed when using mapGetters 

### ISSUE THREAD

**Issue by MartinMuzatko** [vuejs/vuex#1136]
### What problem does this feature solve?
It is not clear from the documentation, why `mapGetters` belong into `computed` and not `methods`.
AFAIK there is computed in contrast to methods, because computed is executed when the component is mounted. However, when you return functions from the store in getters, (e.g. filters like `getUsersByRole`) why do they belong into `computed` then and not methods? Is there a semantic difference?

**Comment by LinusBorg** [comment]
Getters *are* computed properties. Their return value (in your case it's a function, but that's not really important) will be created at runtime from the data you proivide, and will be updated when its reactive dependencies change.

but methods are static, they won't update. so it has to be in another computed property so that can update as well.

**Comment by fnlctrl** [comment]
As explained by @LinusBorg :)

> why do they belong into computed then and not method
Simply put, it won't work if they're put inside `methods`. More info about the differences between `computed` and `methods`:
https://vuejs.org/v2/guide/computed.html#Computed-Caching-vs-Methods

**Comment by MartinMuzatko** [comment]
Thanks a lot! This helped a lot to understand this. I just expected some documentation on this in Vuex. ;)
