### ISSUE TITLE
$store对象中带下划线的函数为什么不能直接调用

### ISSUE THREAD

**Issue by 1209823208** [vuejs/vuex#1138]
#

this.$store._actions.getAllProducts;无效
this.$store.dispatch('getAllProducts')  有用

**Comment by posva** [comment]
It's not meant to be called directly.
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
