### ISSUE TITLE
bug: window npm install,it's error!

### ISSUE THREAD

**Issue by hello-guoguo** [vuejs/vuex#1145]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex.git](https://github.com/vuejs/vuex.git)

### Steps to reproduce
git clone https://github.com/vuejs/vuex.git
cd vuex
npm i
======
and it's error.
error code:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.32.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.32.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-02-01T0
3_38_17_639Z-debug.log

### What is expected?
npm i  ===>success

### What is actually happening?
npm i ===>error

**Comment by kiaking** [comment]
FYI, No problem in my environment macOS 10.13.3, nodejs 9.4.0, npm 5.6.0. It works.

**Comment by ktsn** [comment]
This looks like a problem of chromedriver or your environment. Please investigate where the cause come from a bit more.

**Comment by fnlctrl** [comment]
Hi, thanks for filling this issue. Since your error log is not complete I suppose you failed at `Downloading https://chromedriver.storage.googleapis.com/2.32/chromedriver_win32.zip`.

`googleapis.com` is blocked in China so you'll have to workaround it. You can configure npm to use proxies, or try this method: https://github.com/vuejs/vue-router/issues/261#issuecomment-218618180

**Comment by hello-guoguo** [comment]
@kiaking but my environment is `win7`,`nodejs 8.9.3`,`npm 5.5.1`, rather than as your macOS

**Comment by hello-guoguo** [comment]
@fnlctrl Ok,I got it.
Thx!
