### ISSUE TITLE
Find problem when changing state using Object.assign()

### ISSUE THREAD

**Issue by fxxjdedd** [vuejs/vuex#1196]
### Version
3.0.1

### Reproduction link
[http://jsrun.net/QZZKp/edit](http://jsrun.net/QZZKp/edit)

### Steps to reproduce
uncomment the code in dependency.mutations.SET_STATUS

```
            /* doesn't work*/ 
            // state.status = Object.assign(state.status, status)
            
            /* work */
            state.status = Object.assign({}, state.status, status)
```

### What is expected?
loading status should change to 'false' after 500ms

### What is actually happening?
loading status is always 'true'

---
what is the diff between 

Object.assign({}, state.status, status) // work

and 

Object.assign(state.status, status) // doesn't work

**Comment by ktsn** [comment]
1. `Object.assign` directly mutates the 1st argument and returns mutated 1st argument.
2. Vue's reactive system cannot detect the former one since it just reassign the same object to `status`.
3. For usage questions, we encaurage you to use [forum](https://forum.vuejs.org) or [chat room](https://chat.vuejs.org) since the issue list is exclusively reserved for bug reports and feature requests.

**Comment by fxxjdedd** [comment]
thx!

**Comment by fxxjdedd** [comment]
https://github.com/AnnVoV/blog/issues/10
