### ISSUE TITLE
Inconsistent reference to replaced state

### ISSUE THREAD

**Issue by frissdiegurke** [vuejs/vuex#1243]
### Version
3.0.1

### Reproduction link
[https://jsfiddle.net/frissdiegurke/50wL7mdz/326656/](https://jsfiddle.net/frissdiegurke/50wL7mdz/326656/)

### Steps to reproduce
1. Use `store.replaceState` with some new state object that is not the same as the current state.

### What is expected?
`store._modules.root.state` and `store._modules.root.context.state` should both reference the new state object

### What is actually happening?
`store._modules.root.state` instead still references the old (detached) state object

---
I know that `_modules` is a considered private attribute (as the leading `_` tells me), but I thought I should notify you anyways since this is probably unintentional behavior (e.g. it does block garbage collection of the old state) and could lead to further internal issues.

For namespaced modules the behavior within `_modulesNamespaceMap` is as expected.

**Comment by ktsn** [comment]
Is this appeared as actual problem on your app?

The internal `Module` instance represents each module option but not actual store state/getters/mutations/actions. So if you replace the store state, it is surely different with the one in specified on module option.

Also I don't think it's reasonable to replace all internal module's `state` on every time the store state is replaced since it would be useless processing - they are entirely unused in futher process.

**Comment by frissdiegurke** [comment]
This is no actual problem in my app. I just happened to notice. Due to the different behavior in contrast to named modules I thought I should notify you.
If it is not used anyways and the `_modules` property is indeed considered private, you may just close this. I'm not sure why the direct `Module#state` reference (I don't see getters/mutations/actions on the module itself, only state) exists at all in this case. If it's unused, removing it would probably save some confusion for people who run into similar troubleshooting ;-)

**Comment by ktsn** [comment]
`Module#state` is declared to abstract the `state` option. We can access the initial state by just referring `module.state` (`state` option can be an object or a function returning object).
The other assets can be accessed via `Module#forEachXXX` since we only need to iterate them to register into store. 

[The `installModule` function](https://github.com/vuejs/vuex/blob/dev/src/store.js#L271-L310) may help you to see how `Module` works.

I'm closing this issue since it does not cause an actual problem. Thanks for notice us in any cases 🙂
