### ISSUE TITLE
After refreshing the web page, the value type has changed

### ISSUE THREAD

**Issue by aComputerGeek** [vuejs/vuex#1326]
![](https://s1.ax2x.com/2018/06/30/nLMbe.jpg)

**before**
![](https://s1.ax2x.com/2018/06/30/nLdNO.jpg)

**after**

![](https://s1.ax2x.com/2018/06/30/nLG9q.jpg)

**Comment by OutisJM** [comment]
please don't send email to me, thanks!!!发自我的华为手机-------- 原始邮件 --------主题：[vuejs/vuex] After refreshing the web page, the value type has changed (#1326)发件人：aComputerGeek 收件人：vuejs/vuex 抄送：Subscribed 
before

after


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vuejs/vuex","title":"vuejs/vuex","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vuejs/vuex"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"After refreshing the web page, the value type has changed (#1326)"}],"action":{"name":"View Issue","url":"https://github.com/vuejs/vuex/issues/1326"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vuejs/vuex/issues/1326",
"url": "https://github.com/vuejs/vuex/issues/1326",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "After refreshing the web page, the value type has changed (#1326)",
"sections": [
{
"text": "",
"activityTitle": "**aComputerGeek**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@aComputerGeek",
"facts": [
{
"name": "Repository: ",
"value": "vuejs/vuex"
},
{
"name": "Issue #: ",
"value": 1326
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"vuejs/vuex\",\n\"issueId\": 1326,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"vuejs/vuex\",\n\"issueId\": 1326\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/vuejs/vuex/issues/1326"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351772794\n}"
}
],
"themeColor": "26292E"
}
]
