### ISSUE TITLE
Dynamically registered modules during SSR getting lost on client side state replacement

### ISSUE THREAD

**Issue by rustunn** [vuejs/vuex#1351]
If you register store module during SSR (e.g. store.registerModule('name', storeModule); ) and then do store state replacement on the client side (e.g. store.replaceState(window.__INITIAL_STATE__); ), none of the module methods is accessible from within the component throwing an error (module namespace not found in mapGetters/mapState/-//- ).

Pure client or server side works fine, but hydration seems to break.

**Comment by raisezhang** [comment]
@rustunn   Has this problem been solved?

**Comment by p1pchenk0** [comment]
UP, same issue

**Comment by artjerom** [comment]
Has the problem been resolved? I have the same

**Comment by ItsRyanWu** [comment]
I can access the module state with `store.state.module.data` in client-side but failed when using namespace

**Comment by ItsRyanWu** [comment]
So the reason is that you have registered vuex module in your server-side runtime BUT not in client-side runtime. Unfortunately, the official did not do this for you, so you can register modules by yourself in client-side before mounting app or page.

I assume you divided your modules according to different pages and your module name kept in same with your page route name. So you can do this in your `entry-client.js`

```js
router.onReady(()=>{

    store.registerModule(app.$route.name, {
        namespaced: true,
        state: window. __INITIAL_STATE__[app.$route.name]
    })

    app.$mount('#app')
})
```

done!
