### ISSUE TITLE
Documentation Never Actually Walks You Through Set Up

### ISSUE THREAD

**Issue by matsieftw** [vuejs/vuex#1389]
### Version
3.0.1

### Reproduction link
[https://thereisntoneandyoushouldnotrequirethis.com](https://thereisntoneandyoushouldnotrequirethis.com)

### Steps to reproduce
1. Go to your docs.
2. Read them.
3. Think about whether they would be helpful to someone trying to set up a Vue app.

### What is expected?
Helpful documentation walking you through set up of a Vue app using Vuex.

### What is actually happening?
A lot of info on concepts and no info on actually bringing in Vuex to your application.

---
Vue's documentation in general never actually walks you through setting anything up. It provides a few code snippets and assumes you'll understand. The documentation has been the biggest source of my frustration while using Vue since it never actually explains anything.

For example, on the Vuex installation page, sandwiched between CDN/package manager installation and building from source, you've put that Vuex needs to be instantiated in a module set up. You've provided zero context for this. Is this in the store? Is this for every file you need to access the store in? More importantly, it shouldn't be on the installation page, let alone sandwiched in between different installation methods. Vue's documentation is riddled with these issues. Unfortunately, I still don't actually know enough about how Vue actually works to be able to contribute to the documentation in any way. If I didn't have to use Vue for the project I am on, I would be using React, Redux, & RxJs and have access to meaningful, better written documentation that bothers to walk you through the set up. If Vue actually wants to gain any real traction, you're going to need to actually show folks how to use and set up your tools.

**Comment by LinusBorg** [comment]
Hello @matsieftw 

Thanks for your interest in improving  the documentation.  Before I engage the issues you bring up, I have to make one thing clear:

* We are always thatnkful for input from the community, and are always interested in improving our docs.
* However, when giving feedback, we expect people to do so with a constructive and civil tone.
* Your issue is "riddled" ( to use your wording) with passive-aggressive stabs at the work people from the core team and other contributors have put into this:

So I will ask you to plese change your tone as this conversation progresses, or I will simply close the issue and lock it. 

I will still look at the points you brought up because it might help other people, but even though I can understand the people get frustrated when they feel stuck (it happens to all of us, me and the other core team members included) I don't feel a desire to be the valve for the pressure you built up. so if you keep this tone up, I will simply end the conversation.

-----

Now that this is out of the way, let's get into the matter:

> For example, on the Vuex installation page, sandwiched between CDN/package manager installation and building from source, you've put that Vuex needs to be instantiated in a module set up. You've provided zero context for this. Is this in the store? Is this for every file you need to access the store in? 

I see your point, yet at the same time, And even if someone has read the Vue documentation before going into Vuex, and would have found this section about plugins:

https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin
https://vuejs.org/v2/api/#Vue-use

They might still wonder where to put this and where to call it. So the first point of improvement would be to improve the Vue docs regarding "how to install a plugin", and probably link there from the Vuex docs.

By the way, there's also a hint about Vue.use() in the "Getting Started" section:

![image](https://user-images.githubusercontent.com/1444526/44999680-68671300-afbf-11e8-8165-7bfb979ef97a.png)

> More importantly, it shouldn't be on the installation page, let alone sandwiched in between different installation methods. 

Where should it be, then? It's about how to install Vuex in a module setup (i.e. with webpack), so why shouldn't it be in the Installation section? I'm thankful for clarifications.

So I would like to go on to the next point, but that's all you provided in terms of concrete feedback.

If you have other points you think are unclear, pease go ahead and let me know. You must understand that it's always hard for someone ver familiar with a piece of software to understand which steps might be unclear to a beginner.

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vuejs.org/pull/1788

**Comment by LinusBorg** [comment]
Closing since OP seems not to be interested in actual conversation.
