### ISSUE TITLE
bug: examples\todomvc, when press keyboard enter to delete some todoItem, maybe delete two todoItem

### ISSUE THREAD

**Issue by myadomin** [vuejs/vuex#1390]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vuex/blob/dev/examples/todomvc/store/mutations.js](https://github.com/vuejs/vuex/blob/dev/examples/todomvc/store/mutations.js)

### Steps to reproduce
when edit some one todoItem, clear the todoItem text, then press keyboard enter.

### What is expected?
delete the todoItem

### What is actually happening?
delete the todoItem and anothre todoItem

---
when edit some one todoItem, clear the todoItem text, then press keyboard enter.
it will execute @keyup.enter="doneEdit" and @keyup.esc="cancelEdit" (in page TodoItem.vue).
in page vuex\examples\todomvc\store\mutations.js, mutation:removeTodo.
the mutation:removeTodo will execute twice, so will delete two todoItem.

**Comment by ktsn** [comment]
@myadomin 
Are you sure that it is happening with the exact example code? `@keyup.enter` and `@keyup.esc` cannot be triggered on the same time because they are mapped to different keys (Enter and ESC key). Actually I couldn't reproduce it on my machine.

If this still persists on your environment, could you describe the reproduction step in more detail?

**Comment by ktsn** [comment]
Closing until more info is provided.
