### ISSUE TITLE
Return values from mutation commits.

### ISSUE THREAD

**Issue by adjenks** [vuejs/vuex#1437]
### What problem does this feature solve?
One often wants to get the id of a created object back from the data store. Much like in a database, if you add an object to an array in the store, you want to get it's id so that you can reference it again. When looking up how to do this, I found that you cannot, and I also found that someone else had the exact same inquiry on stackoverflow: https://stackoverflow.com/questions/42404925/return-value-from-vuex-mutation-id-for-newly-created-object#42406872
The response to the question on stack overflow was to use vuex actions, but I don't think that one should have to use an asynchronous action to achieve a synchronous task.
To carry on with the database example, one might use postgresql's "RETURNING" as an analogy. One can perform an insert statement and then say RETURNING thing_id to get the automatically generated id, or whatever other fields they would like.

### What does the proposed API look like?
```
let myReturn = this.$store.commit('ADD_THING",{"name":"new_thing"});
// 'ADD_THING' adds a thing to an numerically indexed object and then returns the number.
console.log(myReturn); // {"id":42,"datestamp":1541145883085}
```

**Comment by OzanKurt** [comment]
7

**Comment by eZanmoto** [comment]
I'd like to add another use case to this feature. I'm writing some logic to resolve state updates based on timestamps. Values are stored with the last time that they were updated at, so when I get an update from a server, I `commit('setValue', {id, node})`, and in the mutation I attempt to resolve the update in a similar way to the following:

    ['setValue'] (state, {id, newNode}) {
      const oldNode = state.values[id]

      let ok = false
      if (!oldNode || newNode.updatedAt > oldNode.updatedAt) {
        Vue.set(state.values, id, newNode)
      }
    }

I want to return a value from the mutation that says whether the new value was accepted or not; if the new value was not accepted, then I want to push the local value back to the server.

Note that this resolution logic can't be placed in an action because of its "atomic" nature.

**Comment by adjenks** [comment]
@eZanmoto, for you and others who are still interested, my workaround for this was to pass a reference to an object as a parameter and then modify the object inside the mutation function. The stackoverflow link I provided has a useful example.

**Comment by m00nk** [comment]
@eZanmoto  you have to use both actions and mutations, because the actions can return the value. So your logic will be like this:

```javascript
actions: {
    setValue(ctx, {id, newNode}){
        const oldNode = ctx.state.values[id];
        if (!oldNode || newNode.updatedAt > oldNode.updatedAt) {
           ctx.commit('setValue', {id: id, node: newNode});
           return true;
        }
        return false;
    }
},

mutations: {
    setValue(s, {id, node}){
        s.values[id] = node; 
    }
}
```

**Comment by Anubarak** [comment]
There is still no answer or feedback?
I would need that feature too.

I have a mutation that stores data from many different actions. In the end all my actions that manipulate my objects for different purposes call the very same mutation where the logic takes place.

If a new object is inserted, everything is fine but if an existing object should be updated I update only the new values and cannot overwrite the entire object because I need to keep the references to this object.

After the mutation I would like to return the current state of the store for the mutated objects. Currently I have a workaround via getter to grab all objects that were modified (inserted / updated) but it would be awesome if it was possible without that.

**Comment by kiaking** [comment]
Hi! Sorry for the late response. Well, this is technically very difficult at the current version of Vuex, because `commit` method could call multiple mutations with the same name (this happens when you have modules without `namespaced` option).

I understand your pain, and I myself have suffered from this too. This is something we should definitely improve in the next iteration of Vuex.

But for now, a recommended workaround would be to reference state after `commit` within actions.

**Comment by adjenks** [comment]
@kiaking 
Thank you for looking into it.

**Comment by kiaking** [comment]
So I think we can close this issue. Sorry for making it open for so long, but as I described, this is technically really hard to do with Vuex 3. We should consider this and take in to the design of next Vuex iteration for sure.
