### ISSUE TITLE
Enforcing me to learn ES6?

### ISSUE THREAD

**Issue by pdcmoreira** [vuejs/vuex#149]
I'm sorry for if this seems like a rant, but why am I forced to know ES6 to even understand the documentation or the examples?

I know it's a better thing and whatnot, but I really don't like its syntax and even if I liked it, I have no time to learn it by now. Vue was all about choice so far, why all of this enforcement all of a sudden?

**Comment by yyx990803** [comment]
Because ES6 **is** JavaScript?

On the other hand - there is indeed an opinion here: if you are building a large, serious application (which is implied because you are learning Vuex, which is dedicated for that purpose), then you **should** learn ES6. And I'm honestly surprised that you have time to learn Vuex and yet don't have time to learn enough ES6 just to understand the Vuex docs.

Note when you are starting to look at Vuex and maybe vue-cli, you are stepping into the opinionated part of the framework, so you have to either accept the opinion or just don't use it.

**Comment by chrisvfritz** [comment]
@pdcmoreira I agree it can be frustrating that there are always new things to learn in JavaScript. 😞  Many of ES6/2015's features are very useful though and [this resource](http://jamesknelson.com/es6-the-bits-youll-actually-use/) can actually help you learn the most important ones in less than an hour! 😃

**Comment by pdcmoreira** [comment]
@yyx990803 It's mainly because I don't like the syntax (the best way I can explain is that I love C-family languages with brackets and colons everywhere and I hate Python's lack of those).

About the time, I don't have time to learn everything, I've just grasped the basics of vue-cli, webpack, vue-route and vuex and man, all that stuff really adds up. I guess I'll just go and follow @crisvfritz 's suggestion and learn ES6.

I agree with you that I'm stepping into the opinionated side of vue, but I'm using it for the sake of good practices, not because my app will be large scale.

Anyways, thank you both for the input.

**Comment by piknik** [comment]
I've looked at Javascript around 2009, and I can honestly say that ES6 makes Javascript more like a "real" language, not that it wasn't real back then too. Since you like C-like languages, ES6 actually makes Javascript even more so like a C-language. My favorite feature being classes. As well, the import/export syntax is a lot like how Java does its imports, but with more flexibility. Another big one is the 'let' and 'const' keywords, so no more global 'var's. That's all that's really essential to make yourself a lot more productive, the rest like lambdas are just syntactic sugar, you can use them or use anonymous function as usual.
