### ISSUE TITLE
validators and type checks for mutations

### ISSUE THREAD

**Issue by indirectlylit** [vuejs/vuex#1490]
### What problem does this feature solve?

In vue, prop validation during development is a great way to catch bugs early. A similar feature would be useful for Vuex mutations.

### What does the proposed API look like?

```javascript
const store = new Vuex.Store({
  state: {
    budget: 0,
    people: {},
  },
  mutations: {
    setBudget: {
      mutation(state, value) {
        state.budget = value;
      },
      type: Number,
    },
    addPerson: {
      mutation(state, value) {
        state.people[value.id] = value;
      },
      type: Object,
      validator(value) {
        return value.id && value.name && value.age;
      }
    }
  }
})
```

**Comment by kiaking** [comment]
It might be nice, though there's a difference between Vue's props since props are not functions, validator is the only way to validate it.

Mutations or actions are functions, you could always do the check of the payload inside a function and I think that's more straight forward. That's how ordinary function would work too.
