### ISSUE TITLE
watch instance method behavior is inconsistent between Vue and Vuex

### ISSUE THREAD

**Issue by ianwalter** [vuejs/vuex#1504]
### Version
3.1.0

### Reproduction link
[https://github.com/ianwalter/vuex-issue](https://github.com/ianwalter/vuex-issue)

### Steps to reproduce
1. Register a watcher in a component with a callback function that prints the new data value and old data value
2. Register a watcher on a store instance with a callback function that prints the new data value and old data value

### What is expected?
That when both watchers are triggered, both of them print the new data value and the old data value.

### What is actually happening?
The component watcher prints the new data value and old data value, while the store watcher only prints the new data value (state) and an empty object (getters, if you haven't defined any). 

---
Before reading the Vuex documentation more closely, I assumed that this method behaved in the same way as it does in a component. Returning getters to the store watcher callback seems to me like returning computed in the component watcher callback. I think the old state data is more valuable too, especially since it could provide the initial state as the old data, something you can't get in an alternative way (like subscribing to mutations which only gives you the new state as well).

**Comment by ktsn** [comment]
Well, it receives the old watching value actually...
If you are talking about the 1st callback, it is not the callback that is called when the value is changed. It is a deriving function to specify which part of state/getters you want to watch or etc. This behaviour is actually the same as Vue's one except for the arguments.

I took a look on your reproduction and it has a problem. You need to replace `oldState.message` with `oldState` on [this line](https://github.com/ianwalter/vuex-issue/blob/master/test.js#L16) because the 2nd callback receives derived value via the 1st callback rather than entire state.

**Comment by ianwalter** [comment]
You are right of course. I made an error trying to boil down my more complex usage to the reproduction. Thank you for your work!
