### ISSUE TITLE
Why can’t I assign a socketio object to state in strict mode? 

### ISSUE THREAD

**Issue by zzzgit** [vuejs/vuex#1518]
### Version
3.1.0

### Steps to reproduce
![image](https://user-images.githubusercontent.com/1060733/54004291-023a9300-4190-11e9-8112-17f8814c1fd1.png)
![image](https://user-images.githubusercontent.com/1060733/54004314-154d6300-4190-11e9-808f-b28bf5396181.png)
![image](https://user-images.githubusercontent.com/1060733/54004330-226a5200-4190-11e9-896e-765daa3626c8.png)

### What is actually happening?
in strict mode, I can't assign socket object to state.
is there a solution?

**Comment by Jinjiang** [comment]
Couldn't see your full project. But I guess the `socket` you pass in is not a _plain JavaScript object_ that leads to error. Because the state must be a _plain JavaScript object_.
Next time if you have more question, it's better to supply more information.
Thanks.

**Comment by zzzgit** [comment]
Because `the state must be a plain JavaScript object.`

Is it in the documentation?

**Comment by Jinjiang** [comment]
https://vuex.vuejs.org/guide/#getting-started
https://vuejs.org/v2/guide/reactivity.html#How-Changes-Are-Tracked
These two pages might be help you understand that. Anyway, you make a point, it might be better to be emphasized on the docs.

**Comment by Jinjiang** [comment]
I made a double-check and found that it triggered this line of code:

https://github.com/vuejs/vuex/blob/0e109e2a38dafdc0c2bd6bd3892bc66cfe252b16/src/store.js#L469

That because you enable strict mode and mutate state directly through a function "`function () { return this._data.$$state }`". I suggest you go search where this function comes from in your project. Or disable strict mode.

About strict mode: https://vuex.vuejs.org/guide/strict.html

Thanks.
