### ISSUE TITLE
When actions returns promise, the property will be ignored

### ISSUE THREAD

**Issue by regchiu** [vuejs/vuex#1581]
### Version
3.1.1

### Reproduction link
[https://codesandbox.io/s/vue-template-5rovy](https://codesandbox.io/s/vue-template-5rovy)

### Steps to reproduce
```js
actions: {
    test() {
      let prom = new Promise((resolve) => {
        setTimeout(function(){
          resolve("DONE"); 
        }, 3000);
      });
      prom['id'] = 10
      console.log(prom) // Object contains id
      return prom;
    }
  }
```
```js
created() {
    let pf = this.$store.dispatch("test");
    console.log("PF", pf); // No id property
    pf.then(res => {
      console.log(res);
    });
  }
```

### What is expected?
The properties of the object should be displayed in the console.

### What is actually happening?
The properties of the object are ignored.

---
Share questions from the forum

https://forum.vuejs.org/t/custom-promise-properties-in-actions/

**Comment by mrichar1** [comment]
OK, I've had a look at the code and the issue seems to come in store.js:

https://github.com/vuejs/vuex/blob/91f3e69ed9e290cf91f8885c6d5ae2c97fa7ab81/src/store.js#L443-L447

If `res` is logged immediately before this, it contains the extra property - however if `res.catch(...)` is logged it no longer contains the property.

I can also confirm that the bug disappears if the app is run in a browser (or private window) without Vue Devtools.

**Comment by ktsn** [comment]
You should not expect that `dispatch` returns your customized promise because it can modify it for several reasons. e.g. devtool hook, subscription, consolidating multiple actions etc.
