### ISSUE TITLE
Doc got empty page

### ISSUE THREAD

**Issue by kossa** [vuejs/vuex#1698]
### Version
3.1.3

### Reproduction link
[http://localhost:8080/](http://localhost:8080/)

### Steps to reproduce
Clone repo
run : npm i
run : npm run docs

in browser open : http://localhost:8080/

### What is expected?
See the documentation

### What is actually happening?
Blank page

**Comment by neelansh15** [comment]
I think the problem may be with your **port**.
I ran the dev branch and it works just fine. No blank page.
But I didn't run it on port 8080 since its corrupted, as I use it too much. You can try clearing your cache, __but__ I would suggest you go into `package.json` and change the port.
  Let me know if this solves the issue @kossa

**Comment by kossa** [comment]
how to change port ?

**Comment by neelansh15** [comment]
Open `package.json`.
Under the scripts section, find this:
```json
"docs": "vuepress dev docs",
```

and change it to **this**:
```json
"docs": "vuepress dev docs --port 3000",
```

Then run it normally with `npm run docs`. It will now run on `localhost:3000`

**Comment by kossa** [comment]
Alright it works fine thank you
