### ISSUE TITLE
Component update triggered when non-referenced Vuex state changes

### ISSUE THREAD

**Issue by dsl101** [vuejs/vuex#1743]
### Version
3.3.0

### Reproduction link
[https://codepen.io/dsl101/pen/bGVYPRG](https://codepen.io/dsl101/pen/bGVYPRG)

### Steps to reproduce
Open the codepen, and show the console. The component only references `state.rootObject.prop1` via a getter and a mutation to increment it. This can be seen when clicking the 'Inc Prop1' button.

When another property is added to the `rootObject` (via the 'Add Prop2' button), the component is updated with no change to the underlying data (`rootObject.prop1`) as can be seen in the console. Calls to `incProp2` can be seen to change this new property value, but no component update is triggered (as expected). Finally, deleting `rootObject.prop2` also triggers a component update, despite `rootObject.prop1` not changing.

### What is expected?
None of the mutations associated with `prop2` would trigger the component bound to `prop1` to update.

### What is actually happening?
Creation and deletion of 'peer' properties of `prop1` are triggering component updates. Mutation of 'peer' properties are (correctly) _not_ triggering updates.

---
This could be my misunderstanding of how Vuex actually works (in version 3), but it is causing my app performance issues when unrelated changes in state are triggering many hundreds / thousands of component updates (with no visible data changing). If there is any way to configure or use Vuex, allowing properties to be added / removed _without_ causing updates of existing properties, I couldn't find it in the documentation.

Note this example could easily be solved by having 2 separate state properties. But this is an example of deeply nested real-world data backed by firestore, so separating all the properties out isn't a workable solution there.

I was also curious to see if Vuex 4 changed this behaviour in any way, but I couldn't find or figure out a codepen setup for Vuex 4 yet—happy to experiment if there is one.

**Comment by cuebit** [comment]
@dsl101 this is expected behaviour and is a by-product of [Vue.set](https://vuejs.org/v2/api/#Vue-set).

Mutating `rootObject` using `Vue.set`, being a reactive property and all, will consequently trigger a reactivity ripple. This is true for mutations that directly affect the layout of an object (i.e. additions/deletions), as you've demonstrated this is not the case when mutating existing state.

> Note this example could easily be solved by having 2 separate state properties. But this is an example of deeply nested real-world data backed by firestore, so separating all the properties out isn't a workable solution there.

Vuex and Firestore are two different services, therefore bridging the two will require some form of intermediate abstraction.

I don't consider this a functional issue and more likely to be a data design issue.

**Comment by dsl101** [comment]
Yes, the more I thought about it, the more I thought the buck would stop with Vue.set. What I'd really like to know is if this is a deliberate design decision or just a side effect of how reactivity is implemented. For example, if I replace a state object (e.g. `rootObject`) with another containing _identical_ properties and values, _should_ that count as cause for a reactivity ripple. Or is it just that the cost of checking whether all those things are identical is not worth the (perceived) cost of a reactivity trigger. I say perceived as, in my case, the cost of the reactivity update is quite high when not needed, but I don't think I have any control over that.

I'd be really interested to hear the views of someone who knows the ecosystem better than I do. If there's no quick easy answer to that, I'll post something to a Vue forum for discussion.

**Comment by kiaking** [comment]
It might be solved at Vue 3 due to the new reactivity system with proxy. In Vue 2, we have limitations such as this when adding/deleting property from the reactive object.

Nonetheless, since Vuex uses Vue's reactivity directly. Even if we do something about this, it has to be raised as Vue's issue.

Thanks for the feedback though! 👍
