### ISSUE TITLE
Adding mutateAction

### ISSUE THREAD

**Issue by noozzz** [vuejs/vuex#1745]
### What problem does this feature solve?
There are confusion about action vs commit among developers.

Many developers suggest to use only dispatch() in components and call commits() only in actions in order to separate responsibilities and to make code reusable. However, someone suggests that it's okay to use commit directly in components when it is so obvious.

In order to take the benefits of both approach, I suggests a simple mutateAction, which can mutate state directly like mutations and called by components in a same way as normal actions. In summary, the mutateAction is an action from the component's point of view, while it is similar to mutation in the store.

With this feature implemented, I think it is safe to insist to use only dispatch() in components.

### What does the proposed API look like?
In the store:
```javascript
mutateActions: {
   setSomeState (state, payload) {
     state.some = payload
  }
}
```
In the components:
```javascript
this.$store.dispatch('setSomeState', payload)
```

**Comment by kiaking** [comment]
Thanks for the proposal! I think it should be considered in the next iteration of Vuex for sure.

First of all, I don't think we need to "insist users use only dispatch() in components". It's OK to commit mutations directly from the component. If you know what you're doing, then the users should be able to use the `commit` method however they want.

As for your proposal, I don't think having `mutateAction` is a way to go. Vuex mutations are for synchronous operation because we have to keep synchronous histories (for example, in dev tools).

The discussion for merging actions and mutations has a long history, and while we do see things that we can improve in this area, we need to have a broader discussion toward the next iteration of Vuex.
