### ISSUE TITLE
State undefined and Duplicate registration for unclear reasons?

### ISSUE THREAD

**Issue by SumNeuron** [vuejs/vuex#1751]
### Version
4.0.0-beta.2

### Reproduction link
[https://gitlab.com/SumNeuron/v-focus](https://gitlab.com/SumNeuron/v-focus)

### Steps to reproduce
npm i 
npm run dev
hover over card

### What is expected?
module only registered once
state is not undefined

### What is actually happening?
module registered many times
state is undefined

---
I have a very simple Vue component and Vuex Module (that I developed in Nuxt but intend to rollup https://gitlab.com/SumNeuron/v-focus). However I am getting some crazy weird issues. 

1st the module (https://gitlab.com/SumNeuron/v-focus/-/blob/master/modules/v-focus.js),

```js
focusMode ({ commit, state }) {
  if (state._focusTimeout) {
    return
  }
  commit('setFocusTimeout', setTimeout(() => commit('setFocusMode', true), state.focusTime))
},
```

I get:
"state is undefined"

As for the component (https://gitlab.com/SumNeuron/v-focus/-/blob/master/components/VFocus.vue)
where I have the these two methods

```js
hasModule() {
  let vuexHasModule = this.$store.hasModule(this.$moduleName) === true
  let doubleCheck = (this.$store.state && this.$store.state[this.$moduleName] !== undefined)
  return vuexHasModule && doubleCheck
},
register() {
  if (!this.hasModule()) {
    try {
      if (!this.hasModule()) {
        this.$store.registerModule(this.$moduleName, VFocusModule)
      }
    } catch (e) {
      if (!this.isSilent) {
        console.error(e)
      }
    } finally {
      this.$emit('register:v-focus')
    }
  }
},
```
I am getting vuex warnings of duplicate registration. How? Does store.hasModule try to register the module itself?

(This is based off nuxtjs's store)

**Comment by kiaking** [comment]
Hi! Thanks for report! However, I need to ask you to drill the issue down a bit more before you submit an issue.

For example, you're using `v3.4.0`, not `v4.0.0-beta.2`. In https://gitlab.com/SumNeuron/v-focus/-/blob/master/components/VFocus.vue, you're mutating props directly at line 86 which you shouldn't. When defining stores, you should do `export const mutations` instead of `export default`.

I'm not sure if any of those matter to your issue, but please understand that looking into this kind of large code to figure out what is going on is very hard for us. Please try creating a minimal reproduction code that illustrate the issue without unrelated things.

Or you may post the questions to [Vue Forum](https://forum.vuejs.org) to get more generic help 👍

**Comment by SumNeuron** [comment]
@kiaking  I can try? but real quick to address what you raised:

Re: version
whoops, sorry I just assumed I was latest. Sorry

Re: line 86: 
> return this.moduleName === '' ? MODULE_NAME : this.moduleName
that is tetrary operator, not assignment

Re: export
I made the change locally and doesnt seem to make a difference

**Comment by kiaking** [comment]
Oh sorry about line 86, my bad 😓 

> I made the change locally and doesnt seem to make a difference

Yea, I was hoping that would had any effects... but as I mentioned, it's just hard to drill down and remove all unnecessarily code at my side. It's much easier to just look into the minimal code base 🤝

**Comment by SumNeuron** [comment]
I mean it is basically as minimal as it can be. Rather than vue-cli for development it uses nuxt, (npm run dev to spin it up). The store is literalyl 3 variables, one boolean, one not used in the component, and the other is null most of the time and the largest part of the component file is the stuff dedicated to registering the vuex module.

**Comment by kiaking** [comment]
Well we've discussed in the Discord and found out that it was thing about `preserveState` option usage and when you call `registerModule` and such.

Please understand that maybe it's easy for you to understand since you wrote it, there're lots clutters in the code things like `try` block which I don't understand what it does. I have to go through all of them before I get to the core because it's not clear what is going on.

Please make sure to nail down the issue when reporting the issue to the GitHub 🙏  Or else Discord or Vue Forum would suit the issue best.
