### ISSUE TITLE
typescript enhancement type Store<any>

### ISSUE THREAD

**Issue by imsunhao** [vuejs/vuex#1769]
### What problem does this feature solve?
when i use vue-property-decorator & vue 2 & typescript, my this.$store always is `Store<any>`，I found a solution

### What does the proposed API look like?
eg:
``` 
this.$store.state.user => (property) user?: Pick<Schema.TUser, "ID" | "name" | "class" | "role">
```

**Comment by imsunhao** [comment]
#1770 This is my solution

**Comment by imsunhao** [comment]
This is an example of a project I provided. [case](https://github.com/imsunhao/student-management-system/tree/feature/vuex-pr)

**Comment by imsunhao** [comment]
in this example,  use @types/vuex.d.ts can redefine TStore

``` typescript
declare module '@imsunhao/vuex/types/default/store' {
  import { Store as S } from '@imsunhao/vuex'
  import { TStore } from 'store'
  type TStore = S<TStore.State>
}
```


so in src/views/app/index.vue

```
export default class APP extends Vue {
  subTitle = '欢迎页面 222'

  get storeUser() {
    return this.$store.state.user // => (property) user?: Pick<Schema.TUser, "ID" | "name" | "class" | "role">
  }
}
```

**Comment by kiaking** [comment]
Thanks for the report! This is known issue and we've fixed it in Vuex 4. We didn't include this in Vuex 3 because technically, it was a braking change.

With your solution, it wouldn't be a braking change, though I don't think adding a `TStore` type is the cleanest way. Doing so with your project is totally valid 👍 Just I don't think it would be a good fit in the core.
