### ISSUE TITLE
Slow registerModule when the module has getters

### ISSUE THREAD

**Issue by mattnathan** [vuejs/vuex#1792]
### Version
3.5.1

### Reproduction link
[https://jsfiddle.net/qaL8f36y/](https://jsfiddle.net/qaL8f36y/)

### Steps to reproduce
0. Open the link
1. Specify any number > 0 for 'getters'
2. Click Generate Modules
3. Click Generate Modules

I was unable to generate more than about 3000 getters in total before the browser crashed.

Without the link, call Store.registerModule to register 1000s of modules with a single getter (or fewer modules with more getters) to see the browser run out of resources.

You can test out creating modules without getters and notice that the time taken is more-or-less constant (~45ms for me)

### What is expected?
Registering modules with getters should perform the same as modules without getters

### What is actually happening?
Performance of Store.registerModule when the module has getters is compounding, the more getters you have the slower it is to add more modules with getters.

---
I'm using dynamic modules as a pattern to handle 'collections of objects' in the store while avoiding needing to pass the index (or object key) around in getters, mutators, etc. Similar to https://stackoverflow.com/questions/44345704/separating-vuex-stores-for-dynamically-created-components - I have hundreds of objects in the store that are treated this way.

I noticed an issue when using the dev tools as the dev tools would frequently crash, and sometimes the page would too. There were repeated warning in the console `[Violation] 'setTimeout' handler took 1552ms` where the time was increasing each time, which I took to mean something wasn't linear/constant time. I finally took the time to create a minimal reproduction but found the issue was present without Vue/Vuex devtools open, though the numbers needed to crash the browser were larger without devtools.

**Comment by kiaking** [comment]
This happens because registering a module forces Vuex to re-evaluate all getters. It's same reason described at [this issue comment](https://github.com/vuejs/vuex/issues/1593#issuecomment-578116958). So every time you add new getters, each registration become slower than before.

Also when you're using Dev Tools, it also dispatch changes in all subscribed watchers to force getter re-evaluation for hot reloading. That's why it becomes even slower when you're using Dev Tools.

Sad to say but module system in Vuex wasn't designed to be used in this way. Although your approach does make sense in theory, I would recommend you to store records in state object, or array (I know you wanted to avoid this but... 😢 ).

For example, [Vuex ORM](https://github.com/vuex-orm/vuex-orm) stores all records with in `data` property in a module, and we have perf test for more than 30,000 records and it gets resolved less than 100ms.

I'm not saying you should use Vuex ORM or anything, I'm just trying to illustrate that the performance issue should go away if you stick to storing records in module state instead of creating a module for each records.

As mentioned at the issue comment, there's not much we can do to fix this problem with current Vuex implementation. We're hoping to avoid this behavior in Vuex 5.

I'll be closing this issue since it's really the same issue with #1593, which I'm thinking to keep it open until we get Vuex version that fixes it 🤝

**Comment by mattnathan** [comment]
Thank you for the detailed response. It's a shame this isn't something that can easily be fixed, but I understand. 

I am a little surprised that this limitation isn't mentioned anywhere in the docs, especially as it's already known.  If I'd read about it there I could have saved myself a lot of time.

**Comment by kiaking** [comment]
Good point yeah. I think it's worth mentioning it in the docs 👍
