### ISSUE TITLE
 Is v3.5.1 incompatible with v3.0.1? 

### ISSUE THREAD

**Issue by so-diao** [vuejs/vuex#1824]
### Version
3.5.1

### Reproduction link
[https://codepen.io/so-diao/pen/oNxGVvW](https://codepen.io/so-diao/pen/oNxGVvW)

### Steps to reproduce
https://codepen.io/so-diao/pen/oNxGVvW

### What is expected?
-

### What is actually happening?
I modified an old project  `package.json -> vuex: '^3.0.1'` , `npm i` automatically downloaded the latest version (3.5.1) for me, but they are not compatible.

Why are incompatible changes occurring?

```js
//  return jquery promise
actions: {
    fetch() {
        const Deferred = jQuery.Deferred()
        setTimeout(() =>{
            Deferred.resolve()
	}, 1500)
	return Deferred.promise()
    }
}

// v3.0.1 success
// v3.5.1 error
this.$store.dispatch('fetch').done(res =>{xxxxx})
```

**Comment by sodatea** [comment]
Just a quick note: it's introduced in https://github.com/vuejs/vuex/pull/1740.
The jQuery promise is now wrapped inside a native Promise, whose keys are not enumerable.

I think the current implementation is more accurate because the documentation has always said the `dispatch` method "returns a Promise that resolves all triggered action handlers". https://vuex.vuejs.org/api/#dispatch

You should not have relied on the `done` method, which doesn't exist in the Promise/A+ spec.

**Comment by so-diao** [comment]
It seems to be added by accident.
I see. Thank you @sodatea
