### ISSUE TITLE
TypeError: Cannot read property 'hasChild' of undefined

### ISSUE THREAD

**Issue by urbnjamesmi1** [vuejs/vuex#1850]
### Version
3.5.1

### Reproduction link
[https://jsfiddle.net/xkLh4njp/](https://jsfiddle.net/xkLh4njp/)

### Steps to reproduce
1. Create a Vuex store.
2. Call store.hasModule() with an array of at least 2 elements where neither module has been registered to the store.

### What is expected?
store.hasModule() to return false

### What is actually happening?
Error "TypeError: Cannot read property 'hasChild' of undefined" is thrown

**Comment by cuebit** [comment]
Thanks for opening this issue and creating a PR. However, this is expected behaviour at this time.

In the same manner as `registerModule` behaves, where a parent module must be registered before any descendants, the `hasModule` should verify the parent before verifying any descendants.

Negating the return type, when checking for a descendant where a parent module _may_ not exist, implies the parent _may_ exist when really you want this behaviour to be explicit.

**Comment by urbnjamesmi1** [comment]
Can the documentation for `hasModule` and `registerModule` at least be updated with this explanation?  Or maybe a custom error can be thrown explaining that a specific parent module doesn't exist.

**Comment by cuebit** [comment]
For sure, this is an opportunity to offer clarity in the docs. I don't think throwing errors are a useful way to identify this concern, since the `hasChild` method naming is self explanatory in the error thrown when a child module cannot be reached.
