### ISSUE TITLE
Order of actions

### ISSUE THREAD

**Issue by Jdruwe** [vuejs/vuex#186]
I am fairly new to VueJs and Vuex and I am having trouble wrapping my head around the following:

I have an <app> component the loads a list of countries from an API when the page '/countries' (default page using vue-router) loads, the result gets stored in the state. When navigating to the attractions page '/countries/:id' I query some attractions (for example an amusement park) of the country that was clicked on ( + set currentCountryId in the state). On this page I also display the name of the country:

`{
    id: 0,
    name: 'Belgium'
  }`

I wrote a Vuex getter funtion that returns the current country from the state (using the currentCountryId from previously). This code all works perfectly fine when the users does not refresh while on the attractions page. 

This is what happens when the user DOES refresh while on the page:

1. both the getCountriesFromServer and getAttractionsFromServer actions get called (both in the created () method) 
2. the following piece of html throws an error in the console because the list of countries in the state has not been populated yet:

`<span class="attractions-country__name">{{country.name | capitalize}}</span>`

![screen shot 2016-05-23 at 21 26 26](https://cloud.githubusercontent.com/assets/4804496/15481864/0bc97caa-212d-11e6-9b02-a0453c7b7654.png)
3. The actions complete and country name gets shown

How can I prevent this behavior?

I know this might be a bit complicated so here is the code: https://github.com/Jdruwe/travel-vue.
Any help would be greatly appreciated

**Comment by jonagoldman** [comment]
Well of course the problem here is that ``country`` is undefined because the countries array is empty until the response returns. To my knowledge you have 3 options:

1) Make vue-router to wait until the promise has returned (probably using a [Transition](http://router.vuejs.org/en/pipeline/index.html)).
2) Don't render that section of the template until ``country`` is defined (maybe using ``v-if`` in the root element/div).
3) Provide an empty default country ``{ id: null, name: '' }`` if the countries array is empty.

Hope it helps, 
maybe someone have a better solution.

**Comment by Jdruwe** [comment]
Thanks, I fixed it at the moment by using `v-if="country"`. Not sure if there are better solutions available.

**Comment by LinusBorg** [comment]
Hello @Jdruwe , 

thank you for your interest in this project.

Github Issues are reserved for bug reports and feature requests. 

For support, please refer to our community forum at forum.vuejs.org
