### ISSUE TITLE
try to add registerModule in router beforeEach

### ISSUE THREAD

**Issue by musashiM82** [vuejs/vuex#1879]
### Version
4.0.0-rc.1

### Reproduction link
[https://github.com/musashiM82/register-module-in-router](https://github.com/musashiM82/register-module-in-router)

### Steps to reproduce
* clone repo
* execute `npm i && npm run serve`
* open web app in browser
* check console error ` [vuex] module namespace not found in mapGetters(): home/`
* click on About link
* check console error ` [vuex] module namespace not found in mapGetters(): about/`

### What is expected?
it is expected that store module is registered in correct way

### What is actually happening?
it is like that store module is not registered

**Comment by cuebit** [comment]
When dynamically loading modules, remember they are resolved as the namespaced object. You still need to read the default module...

```js
import('../store/homeStore').then(({ default } => {
  store.registerModule('home', default)
  next()
})
```

Please visit the [Forum](https://forum.vuejs.org) or [Discord](https://chat.vuejs.org) if you have further questions. Otherwise feel free to open a new issue if you discover a bug.

**Comment by musashiM82** [comment]
thanks
