### ISSUE TITLE
add config to index types, this.$config from Nuxt is not recognised in the store (typescript).

### ISSUE THREAD

**Issue by maartenvanasperen** [vuejs/vuex#1888]
### What problem does this feature solve?
In Vuex the config values from Nuxt are not recognised in Typescript: https://nuxtjs.org/blog/moving-from-nuxtjs-dotenv-to-runtime-config#using-your-config-values. So this.$config is available in the Vuex store and I can access the values, but it says property '$config' does not exist on type 'store'

In any vue component (with TS) it gets recognised and works as intended, but not in the Vuex store.

### What does the proposed API look like?
in vuex/types/index.d.ts add:
`config: any;
`
This resolves the problem and $config gets recognised in the Vuex store. Or is there a better way to extend the index.d.ts? I couldn't find how.

**Comment by kiaking** [comment]
We shouldn't add this to Vuex since there's no `config` property in Vuex. That property should be added at plugin side, in this case, by Nuxt. You could define your own type augments like this maybe.

```ts
// Place the file in your project directory.
// vuex.d.ts

import Store from 'vuex'

declare module 'vuex/types/index' {
  interface Store<S> {
    $config: any
  }
}
```

if this is intended behaviour for Nuxt, then it might make sense for Nuxt to add this. Please file an issue at Nuxt repo 👍
