### ISSUE TITLE
Why do we allow a dispatch to return a promise that can be chained?

### ISSUE THREAD

**Issue by Joralf** [vuejs/vuex#2061]
### What problem does this feature solve?
From the documentation (https://vuex.vuejs.org/guide/actions.html#composing-actions)

> The first thing to know is that store.dispatch can handle Promise returned by the triggered action handler and it also returns Promise:

```
store.dispatch('actionA').then(() => {
  // ...
})
```

This opens up the possibility for a component to "do stuff" after a promise was resolved or rejected. Imho this breaks the unidirectional pattern, cause the component will react to the result of the asynchronous action instead of the state of the store. What was the reasoning behind this decision and what are your views on the above statement?

### What does the proposed API look like?
A dispatch never returns a promise, so we can guarantee the caller follows the unidirectional pattern.

**Comment by kiaking** [comment]
Because sometimes you want to "wait" for some actions to finish, because actions can be asynchronous.

> This opens up the possibility for a component to "do stuff" after a promise was resolved or rejected.

Yes, this is why actions returns a promise. So that component can "do stuff" after the actions are completed. Sometimes we need this.

> Imho this breaks the unidirectional pattern...

I don't think so. It depends on how you would use it. If you don't want to interact with returned promise, just don't use returned value 👍 

---

Closing the issue since this is more of a question rather than issue or enhancement.
