### ISSUE TITLE
Subscribing to store mutations in Vue components

### ISSUE THREAD

**Issue by steffans** [vuejs/vuex#219]
It would be nice to add mutation listeners from a Vue component. Something like `store.subscribe` does in Redux. Right now it is only possible with `middlewares` but these can **only** be added with the `Vuex.Store` constructor.

Im thinking of adding a option called `subscribe` which can be defined in a component.

```js
vuex: {
  getters: {},
  actions: {},
  subscribe: function (mutation, state, store) {
      // listener code ...
  }
}
```

**Comment by yyx990803** [comment]
What is the use case for this?

**Comment by steffans** [comment]
This is useful in order to listen to mutations and do something which is not user interface related since this happens through the getters. For example sending an http request or save an certain state of a variable for undo/redo.

**Comment by LinusBorg** [comment]
I think this simply belongs into actions, doesn't it? 

The number of situations where you would have two *different* actions that call  the *same* mutation and should have the *same* side-effect (forcing us to duplicate thje side-effect in those actions / extracting it into a module...) should be pretty small ...

**Comment by yyx990803** [comment]
With 1.0/2.0 you can just do `this.$store.subscribe((mutation, state) => ...)`

**Comment by steffans** [comment]
@yyx990803 Thanks for your effort! I just started to work with Vuex 2.0

**Comment by mrdezzods** [comment]
How do you unsubscribe an handler?

**Comment by yyx990803** [comment]
@mrdezzods `store.subscribe` returns an `unsubscribe` function.

**Comment by mrdezzods** [comment]
Oh Okey. I was actually going to maken a pull request for that, but I got my answer now 👍

**Comment by ramakrishnamundru** [comment]
@yyx990803 
Can you give a clear example of how to unsubscribe to store mutations, I can't find `unsubscribe` in the source code of vuex, also can't figure how to unsubscribe. using vuex V2.2.1. Thank You

**Comment by LinusBorg** [comment]
Hello ..

Thank your for your interest in this project.

This is a closed issue. Furthemore, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
