### ISSUE TITLE
Are container components useful?

### ISSUE THREAD

**Issue by caliber01** [vuejs/vuex#229]
Hello. I have been recently looking into the React + Redux stack and found this very popular pattern to separate container components (those which interact with the Flux part of the app) from presentational components (those that only display the data they receive). Is there any benefit to have such separation in Vue components? Thank you.

**Comment by LinusBorg** [comment]
Hello caliber01

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
