### ISSUE TITLE
2.0 modules

### ISSUE THREAD

**Issue by pdcmoreira** [vuejs/vuex#241]
Is Vuex 2.0 working with modules?

I have a configuration module:

```javascript
const state = {
    locale: {
        available: [],
        current: null,
        mode: null
    }
}

const getters = {
    all (state) {
        return state.configuration;
    },
    
    locale (state) {
        return state.configuration.locale;
    }
}

const mutations = {
    LOAD_CONFIGURATION (state, config) {
        state.locale = config.locale;
    },
    
    SET_LOCALE (state, locale) {
        state.locale.current = locale;
    }
}

export default {
    state,
    getters,
    mutations
}
```

I'm able to access the state through `this.$store.state.configuration`, but I can't call any getter.
I would expect that doing something like `this.$store.configuration.all` or `this.$store.configuration.getters.all` or even `this.$store.getters.configuration.all` would work, but they don't (all of them give me undefined errors).

**Comment by ktsn** [comment]
Getters in a module in Vuex 2.0-rc.1 receives the state of its module, not root state.
So, your getter should be like following code and it would work.

```js
const getters = {
    all (state) {
        return state;
    },

    locale (state) {
        return state.locale;
    }
}
```

And all getters are put on `store.getters` flatly. you can access your getters from `this.$store.getters.all` or `this.$store.getters.locale` 😃

**Comment by pdcmoreira** [comment]
Shouldn't the getters be "namespaced"? Like `this.$store.getters.configuration.all`? It doesn't make sense that we're dividing our state in modules and then the corresponding getters are all flat.

**Comment by ktsn** [comment]
Getters should hide "the way how to get a sub state tree" from components because of improving application maintainability.
if Vuex namespeces module getters, the structure of the state tree is leaked to components and we lose the one of benefits of getters.

I think, application developers should be responsible about namespaces of getters and others.
Similarly, automatic namespaces for actions and mutations are discussed in #236 and it is removed from 2.0 by discussion.
Does this answer make sense?

**Comment by pdcmoreira** [comment]
Yes, but for a huge application that has several modules, like Document Management, File Storage, Commercial Activity, Support, (...), do you really want to have 200 getters, like `this.$store.getters.documentManagementGetPending`? Or would you rather do `this.$store.getters.documentManagement.pending`? It looks a lot cleaner to me to have "namespaces" than to prefix everything. Again, I'm talking about huge applications, which is where Vuex makes sense.
Actually, I think that it shouldn't even be limited to one level, because it may have sub-modules, like `this.$store.getters.documentManagement.erpIntegration.pending`, but maybe that's asking too much.

**Comment by ktsn** [comment]
Hmm, as you said, it may be strange to prefix to them.
Actually, I'm using Vuex in a huge system too and writing prefixed and flatten getters, but I don't feel resistance about that. (It's Vuex 1.0 but I'm writing getters in the same structure to 2.0)

I guess it is because I rename the getters when I use them in components.
In Vuex 2.0, `mapGetters` helper can map getters to renamed and computed property.
```js
export default {
  computed: mapGetters({
    integration: 'documentManagementErpIntegration'
  }),
  created() {
    console.log(this.integration)
  }
}
```

If this does not make sense for you, could you explain painful situation when you use such getters?
It probably helps the improvement of Vuex :)

**Comment by yyx990803** [comment]
Closing since getters are supported in modules now.
