### ISSUE TITLE
How to trigger a function after some state in store has changed?

### ISSUE THREAD

**Issue by zhuqiuyang** [vuejs/vuex#256]
I want to do something after some state has been changed in one component,like router jump and so on.
Now i accomplish it by watch the state from getters method?
Did exits any other good ways?

**Comment by LinusBorg** [comment]
Well, either you do that at the source of the change (where the action is called), or in the action itself.

**Comment by LinusBorg** [comment]
@
Hello ..

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).

**Comment by zhuqiuyang** [comment]
@LinusBorg ok,i notice it,thank you.
