### ISSUE TITLE
UI not updated, why do I need to commit states to see changes?

### ISSUE THREAD

**Issue by edouard-lopez** [vuejs/vuex#272]
When I load my page, I fetch a list of [`optboxes` items](https://github.com/Coaxis-ASP/opt/tree/eb236f4e004e3b8cc492929c4ef10b1ddfaeec42/frontend/src/pages/optboxes/optboxes.vue). 

### Sources

Project's sources are online:
* [`optboxes` page](https://github.com/Coaxis-ASP/opt/tree/eb236f4e004e3b8cc492929c4ef10b1ddfaeec42/frontend/src/pages/optboxes/optboxes.vue) ;
* [store](https://github.com/Coaxis-ASP/opt/tree/eb236f4e004e3b8cc492929c4ef10b1ddfaeec42/frontend/src/store) (store, actions, mutations, getters).

### `optboxes` pages 

The HTTP request is well send and return adequate data:

```
created(){
    this.getOptboxes();
},
components: {
    'optbox': OptboxComponent,
},
methods: {
    getOptboxes() {
        optboxes.all().then((response) => {
            this.setOptboxes(response.data.output);
    }).catch(() = > {
            this.no_optbox_message = 'there is no optbox';
        logging.error(this.$t('optboxes.get.failed'))
    });
    }
},
vuex: {
    actions: { setOptboxes: actions.setOptboxes},
    getters: { optboxesList: getters.retrieveOptboxes}
}
```

 I'm iterating over the results as follow:
```
<div v-for="optbox in optboxesList" class="panel panel-default">
     <optbox :optbox="optbox"></optbox>
</div>
```

### Question

If I switch to another pages and come back then the list appear. I also notice that with the Vuex extension I can commit the state and see the changes.

Why are my changes not applied automatically?

**Comment by ktsn** [comment]
Looks like you add new property in [your mutation](https://github.com/Coaxis-ASP/opt/blob/eb236f4e004e3b8cc492929c4ef10b1ddfaeec42/frontend/src/store/mutations.js#L6). You have to use `Vue.set` to add new property on an object because of the restriction of Vue's reactivity system.
Please see http://vuex.vuejs.org/en/mutations.html#mutations-follow-vues-reactivity-rules.

I recommend you to ask such question on [the vuejs gitter](https://gitter.im/vuejs/vue) or [the vuejs official forum](http://forum.vuejs.org/).
