### ISSUE TITLE
@input works for select tag in Chrome, but not Firefox

### ISSUE THREAD

**Issue by nicolechung** [vuejs/vuex#289]
I think for the select tag, it should only work for @change. I imagine @input should only for for text input.

I noticed that @input worked for a select box I wrote. It worked in Chrome, but not Firefox (latest versions of both in Mac). I am still learning the api so I used @input by accident. 

Perhaps there should be an error message if someone tries to use @input for a select box to force them to use @change instead.

Also, what do you use for radio and checkboxes - @change?

**Comment by ktsn** [comment]
Thanks for filling issue @nicolechung!

However, I think providing error messages for unsupported events is not responsibility of Vue.js.
There are various behaviors for each browser not only input events, and there are no worth for providing warnings for them.

But if you really think this makes sense, please open this issue on [Vue.js core repository](https://github.com/vuejs/vue). Vuex cannot do this for you because Vuex does not handle DOM events.
