### ISSUE TITLE
Need suggestion: vuex for large projects.

### ISSUE THREAD

**Issue by saknarak** [vuejs/vuex#294]
How a module has their own actions and getters?
How component access module's store

```
vuex/
  store.js  (global store)
  actions.js
  getters.js
  modA/
    store.js
    actions.js
    getters.js
  modB/  (same structure as modA)
  modC/  (same structure as modA)
```

vuex/store.js
```
...
export default new Vuex.Store({state, mutations, getters, actions, modules:{modA, modB, modC}})
```
vuex/modA/store.js
```
...
export default new Vuex.Store({state, mutations, getters, actions})
```
components/App.vue
```
import store from '../vuex/store'
import modA from './ModA.vue'
import modB from './ModB.vue'
import modC from './ModC.vue'
export default new Vue({
  el: '#app',
  store,
  components: {modA, modB, modC}
});
```

components/ModA.vue
```
<script>
export default {
  created() {
    console.log('getters', this.$store.getters); // a lot of getters here
    // 
  }
}
</script>
```

**Comment by ktsn** [comment]
All actions, getters and mutations in each module are registered on same namespace with other modules.
So, if we want to ensure our module is well-isolated for a large application, we should prefix or suffixing its mutation, action types and getter names.

This is because components should not know store's structure. And auto-namespacing is sometimes painful when we want to dispatch multiple actions or mutations via one event.
