### ISSUE TITLE
The example of shopping-cart is can't run. 

### ISSUE THREAD

**Issue by james9527** [vuejs/vuex#300]
The example of shopping-cart is can't run. And the error is "nodejs\\node_modules\\npm\\bin\\npm-cli.js"

**Comment by ktsn** [comment]
Hi, @james9527.

Thank you for filing this issue. However, your issue seems to be a support question.
Please use [our gitter chat room](https://gitter.im/vuejs/vue) or [official forum](http://forum.vuejs.org/) to ask your question.

If you really think the problem is in the example code or Vuex itself, feel free to reopen this and please provide more detailed information. (e.g. your node.js and npm version, the whole error messages)

Thanks.
