### ISSUE TITLE
Is there any way for me to get vuex plugins in mutations

### ISSUE THREAD

**Issue by githubFree** [vuejs/vuex#319]
is there any way for me to get vuex plugins in mutations

**Comment by LinusBorg** [comment]
Hello @githubFree,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) or on [gitter](http://gitter.im/vuejs/vue).
