### ISSUE TITLE
Request that unit tests be added to the vuex examples.

### ISSUE THREAD

**Issue by nueverest** [vuejs/vuex#324]
I am aware of [this page](http://vuex.vuejs.org/en/testing.html), but feel many of us who are just starting out with vuex and vuejs would benefit from seeing unit tests in the examples.  Also, the link provided doesn't show how to test getters just actions and mutations.

**Comment by ktsn** [comment]
Thank you for pointing this out!
We will take it into 2.0 doc.

**Comment by uoziod** [comment]
Would be also cool to have a sample of testing actions with promises (not only callbacks)

**Comment by ktsn** [comment]
Well, it should be easy to convert from callback version to promise version.
It may be verbose to include both version into docs, I think.

**Comment by ktsn** [comment]
Added getter testing. http://vuex.vuejs.org/en/testing.html#testing-getters

**Comment by dbooom** [comment]
Not to create separate issue.
I guess another example may be helpful that shows how components that rely on injected vuex store can be unit tested

**Comment by sohail85** [comment]
to me the documented example to test actions is still a mystery, I am not sure if it is same for everyone or just me since I do not have experience in unit testing, i would appreciate to provide more details, the documentation is so brief, if someone has any useful article to  share I would appreciate
