### ISSUE TITLE
how do I use mapGetters when getters in module

### ISSUE THREAD

**Issue by whyming** [vuejs/vuex#342]
// store.js
import someModule from "./modules/someModule"
export default new Vuex.Store({
    modules:{
        someModule,
        ..........
    }
})

//someModule.js

export default {
    state: {
     data:[1,2,3]
    },
    getters:{
        data: state => state.data
    }
}
//someComponent.vue
computed:{
 mapGetters({
        "someModule:data" // or someModule.data is also not ok
 })
}

can i use mapGetter/mapActions/mapMutations when i have some Modules?

**Comment by SevenOutman** [comment]
meet with the same problem.
how did you solve this?

**Comment by SevenOutman** [comment]
Well I checked the `$store` object and found the getters flattened.

**Comment by Glidias** [comment]
From what i remembered based on the documentation, since module getters are registered to global namespace,  there's a danger that they can conflcit with the root namespace. Thus, it's best to prefix the getters with "something:" within the module, but this must be done manually or through some helper standardised approach means.
