### ISSUE TITLE
where should i regist my plugin

### ISSUE THREAD

**Issue by Force-Wj** [vuejs/vuex#353]
I find a problem in my work. Both my plugin and store need anthor Instance when  initializing
like this:
 var plugin = new Plugin({
       store: store
       callback:function(){
          this.store.commit('someting')
      }
}})
new Vuex.Store({
  actions  :{
   do: function({ commit, state },data){
    plugin.hander(data,()=>commit('XXX'))
   }
  }
})
I solve this problem with ugly method=.= .So
can vuex  provide a dynamic plug Registration and I  visit it  from action‘s arguments or please give an idea to solve this problem
Thanks

**Comment by LinusBorg** [comment]
Hello @Force-Wj,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by Force-Wj** [comment]
@LinusBorg  i think this is a feature request.....  I can't find an elegant way to inject my plugin instance when i deal with action's callback

**Comment by ktsn** [comment]
What is a use case of this?
