### ISSUE TITLE
logger plugin missing from /dist/ folder in 1.0.0 release

### ISSUE THREAD

**Issue by amant** [vuejs/vuex#363]
I was using vuex 1.0.0-rc, and recently upgraded to 1.0.0

`import createLogger from 'vuex/logger';`

On trying to use createLogger plugin, I get this warning: 
 `Module not found: Error: Cannot resolve module 'vuex/logger'`

logger.js used to be inside root directory of /vuex, but now it is neither there or in /vuex/dist like in vuex 2.0.0.

**Comment by ktsn** [comment]
Hmm, the build script on 1.0 branch is not changed so we should able to load it but it's not in `node_modules/vuex`...
/ping @yyx990803

**Comment by nerdyglasses** [comment]
I ran into the same problem now. Somehow the version I was using before isn't working anymore.
Version `1.0.0-rc.2` worked for me before but stopped working after a new `npm install` today.

Trying to fix it. Can anyone confirm `dist/logger.js` has ever existed?

**Comment by nerdyglasses** [comment]
okay I'm pretty sure it never existed in `dist/` but it has been in the root folder back in version 0.5.0.

I believe it has todo with the build process and what will be sent to the npm registry.

I've downloaded both [vuex-1.0.0-rc.2.tgz](https://registry.npmjs.org/vuex/-/vuex-1.0.0-rc.2.tgz) and [vuex-1.0.0.tgz](https://registry.npmjs.org/vuex/-/vuex-1.0.0.tgz).

⚡ tar xvfz vuex-1.0.0-rc.2.tgz
x package/package.json
x package/LICENSE
**x package/logger.js**
x package/dist/vuex.js
x package/dist/vuex.min.js
x package/src/index.js
x package/src/override.js
x package/src/util.js
x package/src/plugins/devtool.js
x package/src/plugins/logger.js

⚡ tar xvfz vuex-1.0.0.tgz
x package/package.json
x package/README.md
x package/LICENSE
x package/dist/vuex.js
x package/dist/vuex.min.js
x package/logger.d.ts
x package/src/index.js
x package/src/override.js
x package/src/util.js
x package/src/plugins/devtool.js
x package/src/plugins/logger.js
x package/types/README.md
x package/types/index.d.ts
x package/types/vue.d.ts

As you can see here `package/logger.js` is missing in the `1.0.0` built.

I've pushed nerdyglasses-vuex with version 1.0.0 to npm.
`logger.js` is present there.

You have two options to hotfix this for now.

Download [logger.js](https://gist.github.com/nerdyglasses/c6ad82192134bdbcbbbef6f0d7dcf124) and place it into your `node_modules/vuex` folder

Or reference the package I've created in your project until it has been fixed in the official repo.
https://www.npmjs.com/package/nerdyglasses-vuex

Best,
Christian

**Comment by codeofsumit** [comment]
same here. A new npm install broke my current version

**Comment by ktsn** [comment]
@yyx990803 Can we release v1.0.1 that include logger.js?

**Comment by nerdyglasses** [comment]
that would be awesome 👏
katashin <notifications@github.com> schrieb am So. 16. Okt. 2016 um 07:10:

**Comment by nerdyglasses** [comment]
Actually it would be better to republish version 1.0.0 since the code doesn't change.
It doesn't change the code at all.
It just a mistakenly missing file in the publish process.

**Comment by ktsn** [comment]
In my understanding, we cannot republish same version more twice to npm. We can only do publish new version.

**Comment by nerdyglasses** [comment]
oh you're referring to this: http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f
I didn't publish something for a long time. so you're right.
But it might be good to unpublish version 1.0.0 then.

**Comment by mlaccetti** [comment]
Never unpublish.  `npm` should remove that functionality totally.  Just publish a new version and leave this bug as history.

**Comment by nerdyglasses** [comment]
@mlaccetti I'm curious why you have that opinion.

**Comment by fnlctrl** [comment]
@nerdyglasses  google "npm left pad chaos" 😂

**Comment by yyx990803** [comment]
Fixed in 1.0.1
