### ISSUE TITLE
Is it possible to attach an indexing DB to the Vuex store and not mess everything up with computed properties?

### ISSUE THREAD

**Issue by dschissler** [vuejs/vuex#382]
Is there a way to do expensive operations in getters so that the data can be pre-indexed?  The most efficient way to do this in my case is to index some data as it is going in and for this I use [nedb](https://github.com/louischatriot/nedb) database but there are many other types of databases like this.  I think that it will be too slow to filter the data each time that I need to access it.

**Comment by LinusBorg** [comment]
Hello @dschissler,

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
