### ISSUE TITLE
How to manage actions in complex project? vuex@2.0

### ISSUE THREAD

**Issue by leaves4j** [vuejs/vuex#384]
I find it's difficult to manage actions when the project is complex，I can't set all the actions in one file, I split those actions into different file, but it's confusing for others when they add an action, maybe the action name is existed.
Is there any possible to add namespace or module likely in actions?

**Comment by LinusBorg** [comment]
Hello @leaves4j 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests.

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by leaves4j** [comment]
This issue is NOT a usage/support question，I think the design pattern in actions can't support complex project, so I suggest some feature in actions like add namespace or module

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vuex/issues/380
