### ISSUE TITLE
Can't access getter from store module

### ISSUE THREAD

**Issue by rightaway** [vuejs/vuex#385]
If I register a module like this

```
store.registerModule('sub', {
  state: {
    A: 'a',
  },
  getters: {
    B: (state) => {
      return doSomething(state.A);
    }
  }
});
```

Then in my component I can do `$store.state.sub.A`, but I can't get access to the getter `B`. `$store.getters` is empty and so is `$store.sub`.

**Comment by ktsn** [comment]
Could you provide reproduction code by jsfiddle.net for this?

**Comment by rightaway** [comment]
Actually I've just realized the mistake was mine for assuming that getters are keyed under the module name like state is. So it's `$store.state.sub.A` but not `$store.getters.sub.B`. Just curious if there was some reason it was designed like this, with the inconsistency between state and getters?

**Comment by LinusBorg** [comment]
http://vuex.vuejs.org/en/modules.html See section about Namespacing.

**Comment by ktsn** [comment]
The doc does not have the reason that getters are registered in global though...
Because getters have higher tolerance for changing module structure by separating with it.
We don't have to change the parts using getters even if we change module structure, because the getters completely independent on module structure.
