### ISSUE TITLE
why wrong on the npm packages when run example: counter

### ISSUE THREAD

**Issue by peterlevel1** [vuejs/vuex#422]
Counter.vue

import Vue from 'vue'

// import Vuex from '../../src'
// this `src` is ok
// ====================
// bug here:
// so weird:
// example run perfectly with github dev version
// but wrong with npm package when 
// import Vuex from 'vuex'
// vuex is installed from npm, so sth happen: 
// ===============================
//vue.common.js:2611[Vue warn]: Property or method "count" is not defined on the instance but //referenced during render. Make sure to declare reactive data properties in the data option. 
//warn @ vue.common.js:2611has @ vue.common.js:508module.exports.render @ Counter.vue?//655a:2Vue._render @ vue.common.js:2238(anonymous function) @ //vue.common.js:1693get 
// ........................
// ===============================

import Vuex from '../../dist/vuex'
//this `dist` is also ok  

// npm version: vuex@2.0.0

**Comment by ktsn** [comment]
Hello, @peterlevel1. Thank you for interested in this project.
However, your issue seems a usage/support question.
Please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask the question because the issue list is reserved for bug reports and feature request exclusively.
We are happy to help you out there.
Thanks.

**Comment by peterlevel1** [comment]
thank you for replying me any way ! 
as the gitter I userd before would not receive replies about one year ago on the vuejs gitter chat room, so I point out this issue hoping you would find the bug why 2 packages are different
I would have a talk with you guys if more things found
