### ISSUE TITLE
Does Vuex work with new Map(), as in key/value map lists?

### ISSUE THREAD

**Issue by Sarke** [vuejs/vuex#439]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

My state for a module looks like this:

```javascript
const state = {
	loaded: false,
	items: new Map(),
}
```

I'm having some issues when updating an item in the list through a mutation, that it doesn't propagate through to the Vue component.  In the component I have:

```javascript
computed: {
	item() {
		return this.$store.state.module.items.get(this.pk)
	},
},
```

Am I using this wrong, or does Vuex not support Map()?  If it's not supported, where would be a good place to put a `load(pk)` method?

**Comment by simplesmiler** [comment]
Hi, thanks for your interest in the project.

The problem is twofold:
1. Vue reactivity system does not (yet) support Map, Set and their weak counterparts. There's a discussion on the topic: https://github.com/vuejs/vue/issues/2410
2. Store data should be serializable, and there is not standard way to serialize Map and Set into JSON.

**Comment by Yamakaky** [comment]
Is there a way to use Map and Set with vue/vuex and some boilerplate, or is it just not supported at all?

**Comment by raghuvarbisht** [comment]
https://stackoverflow.com/questions/58421221/using-a-map-inside-of-vuex-state
