### ISSUE TITLE
Vuex pattern vs Redux mutate state

### ISSUE THREAD

**Issue by ArielGueta** [vuejs/vuex#493]
Hey,

Moving from React and Angular to this great framework I would like to know why in Vuex you can mutate the state?

In Redux you must return a new state ( new reference ) for performance optimizations, how Vue is different?

Thanks.

**Comment by simplesmiler** [comment]
Hello!

This is a usage question, and we encourage you to ask it on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). We try to use the issue tracker for bug reports and feature requests.

As for the question, Angular 1 employed dirty checking (comparing state copies before and after) to figure out what exactly has changed. Both Vue and React approaches are improvement on this, but they are quite different. React embraces immutable data because it's very cheap to compare old and new state by reference instead of checking every property for equality. Vue embraces mutable data and set's up reactive setters that "record" changes, so there's no need to compare at all.
