### ISSUE TITLE
Why getters state on vuex store not updating when using v-model

### ISSUE THREAD

**Issue by DevEclipse** [vuejs/vuex#518]

**Comment by LinusBorg** [comment]
Hello @DevEclipse 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
