### ISSUE TITLE
getter how update Mutations

### ISSUE THREAD

**Issue by dongm2ez** [vuejs/vuex#522]
export const getAuth = (state) => {
  Object.assign(state.account.auth, {
    check() {
      return this.id !== null && this.id !== 0;
    },
  });
  return state.account.auth;
};

i want use getAuth.check() any where

**Comment by LinusBorg** [comment]
Hello @dongm2ez 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
