### ISSUE TITLE
how to get store.state.count in other way?

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/vuex#523]
Don't want to use computed
```
computed: {
    count () {
      return store.state.count
    }
```
Bacause the count is changing all the time,and I will use it only at a certain moment.
Do you have a better way?

**Comment by LinusBorg** [comment]
Hello @hezhongfeng 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by hezhongfeng** [comment]
Thank you.
