### ISSUE TITLE
how to use  ...mapMutations

### ISSUE THREAD

**Issue by DasonCheng** [vuejs/vuex#546]
```javascript
//...
const store = new Vuex.Store({
  state: {
    count: 1
  },
  mutations: {
    increment (state) {
      state.count++
    },
    decrement(state, payload){
      state.count -= payload.amount
    }
  }
})

//...

store.commit('increment')
//or
...mapMutations([
  'increment'
])
//or
...mapMutations({
  add: 'increment'
})

store.commit('decrement', {
  amount: 10
})
//or
store.commit({
  type: 'decrement',
  amount: 10
})

/**
 *how to use ...mapMutations
 */
```

**Comment by LinusBorg** [comment]
Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
