### ISSUE TITLE
pass initiation data to components by injecting dynamic js script containing initial state of the vuex.store.state

### ISSUE THREAD

**Issue by twiggg** [vuejs/vuex#557]
Good morning,

I am faced with a challenged:
trying to build a web app (web client) served by a golang webserver, making calls to an api server to get its data/payload.

Here is my strategy:
user makes a GET request to  domain.com/some/url/path, web server handles it, makes a call to the api, gets some data back and sends a response following the procedure here after:
1) fetch html template
2) compile template embedding data from the api response (the data in inserted as a js script, declaring a new Vuex.Store with pre-populated state, placed at the top of the html body). at the end of the html body, a call to an external javascript is made (loading the actual web app logic and mounting components)
3) send compiled html

I am expecting the Store declared in the body, to be global. (which is the case because I can log it in the console in the app.js mounting the root vue instance). Therefore in the app.js I retrieve the store and bind it (passing store option in new Vue) to every child of the root vue instance attached to a <div id="app"></div> in the body, between the embedded <script>//declaring the store</script> and the <script src="app.js"></script> ...

the issue is that when trying to access the stat with this.$store.state it does not work  and I get a
TypeError: undefined is not an object (evaluating 'this.$store.state')

Am I doing something wrong or is it just impossible ? The very important part of what I am trying to do is to inject data in the store without the need of a subsequent api call ... better for SEO and latency in my opinion, and easier to let the fronted web server and api server handle authorization, data and context.

**Comment by twiggg** [comment]
Here is a very simplified version of what I am trying to achieve, replacing calls to this.$store.state to direct access to global "Store" variable when committing.

https://github.com/twiggg/simple_vuex_vuejs_golang

**Comment by ktsn** [comment]
Not sure if I understand correctly your reproduction but it looks like you are loading two each instances of Vue and Vuex (loaded by `<script>` and bundled by webpack). And it causes this problem.
Vuex is registered automatically to window.Vue (loaded by `<script>`), but you use webpack bundled Vue. So the root instance does not inject store instance to descendants.

BTW, You may want to write the initial state object into `<script>` instead of a store instance and use `replaceState` method as [vue-hackernews-2.0 does](https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/client-entry.js#L6).
