### ISSUE TITLE
View does not update after `$store.state.array[i].attr = 'value'`

### ISSUE THREAD

**Issue by meathill** [vuejs/vuex#582]
I write an electron app recently, and now I am facing a very weird problem.

In the mutation, I wrote like this ([Source 29-31](https://github.com/meathill/Meart/blob/master/app/store/mutations.js))

```
[types.EDIT_ARTICLE] (state, {id, key, value}) {
    state.articles[id]['lastModifiedTime'] = Date.now();
    state.articles[id][key] = value;
}
```

In the component ([Source 36-38](https://github.com/meathill/Meart/blob/master/app/site/Article.js))

```
computed: {
  article() {
    return this.$store.state.articles[this.id];
  }
}
```

after `this.$store.commit`,  the view does not auto update, but I can view the data change from vue-devtool; then if I click the last commit, or `commit all`, then every change will auto update the view.

I have tried `array.splice`, `array = array`, `Vue.set`, or everything I can find on google, but none of them works. Then I want to open an issue so I created a small fiddle, but it works...

Could anybody give me some advice, or some inspiration? With much appreciated.

**Comment by znck** [comment]
Your issue seems usage/support question. If you want to ask such question, please use our [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.

---------
Also, [in store/index.js (L30)](https://github.com/meathill/Meart/blob/master/app/store/index.js#L30), could you explain what is default state? (On forum 😉)

**Comment by lostncg** [comment]
For those who came here accidentally, you may looks for solution here
[stackoverflow link](https://stackoverflow.com/questions/42807888/vuejs-and-vue-set-update-array)
