### ISSUE TITLE
Mutating state

### ISSUE THREAD

**Issue by kalken** [vuejs/vuex#613]
Hello!

Quick question:

Coming from react/redux into vue/vuex i came across a question that is a bit unclear (gave google about an hour).

When mutating states in redux we never want to change the original objects, but return new objects (for example changing properties of an object).

let me give you an example:
i have a list of "fields" where each field has keyproperties that can be changed.

the reducer in redux looks something like:

```
case types.RESOURCE_FIELDS_UPDATE:
  return [
    ...state.slice(0, action.index),
    Object.assign({},
    state[action.index],{[action.key]: action.value}),
    ...state.slice(action.index + 1)
  ];
```

moving to vuex i could simply write:
```
updateField (state, { field, key, value }) {
   state.fields[state.fields.indexOf(field)][key] = value
}
```

So my question is: How should i think about state in vuex? Is it ok to change the actual objects in an array or should i do as i did in redux, e.g creating new objects with changed properties? And what implications does this have for future possibilities of time travel through states etc?

**Comment by ktsn** [comment]
Hi, thanks for your interest in this project.
However, as the issue list is exclusively reserved for bug reports and feature requests, please use [our forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) to ask your question.
Thanks.

---

In Vuex, mutating state object is perfectly valid because it utilizes Vue's reactivity system under the hood.
