### ISSUE TITLE
Mutation not firing in specific cases

### ISSUE THREAD

**Issue by belisarh** [vuejs/vuex#62]
Hello,

**The problem:**
Mutation or otherwise action which fires the mutation does not fire predictably.

**The circumstances:**
_Having:_
An input element with `@focus` and `@blur` event listeners that trigger the visibility a `<div>` element on the page.
The `<div>` contains an `<ul>` with each `<li>`  having an `@click` event listener which fires a store action.

**Expected behavior when clicking on the `<li>`**
The store action should be called.
The mutation should be fired by the action and change the application state.
The `<div>` should disappear as the input lost focus on clicking the `<li>`.

**Actual behavior when clicking on the `<li>`**
**Sometimes**
The store action is **not** called.
The mutation as a consequence is **not** fired.
The `<div>` **does** disappear as the input lost focus on clicking the `<li>`.
**Sometimes** it acts as expected.

Using Vue.nextTick (needlessly) on data change had no effect as expected.
Having the `<div>` always visible eliminates the problem and actions fire as expected.

**Comment by yyx990803** [comment]
This actually is not related to Vuex, and even not directly caused by Vue: the blur event fires before the click event, and before the click event is caught, the element that is supposed to catch the click event has already been hidden - thus the click event is never caught. That's actually just how the DOM works, so you'd get the same result if you just use vanilla JavaScript.

The work around is use `mousedown` instead. Related: http://stackoverflow.com/questions/10652852/jquery-fire-click-before-blur-event

**Comment by belisarh** [comment]
Aha! First time encountering this scenario. Awesome! Thanks for the amazing work,
