### ISSUE TITLE
vuex is undefined

### ISSUE THREAD

**Issue by shuang6** [vuejs/vuex#621]
package.json
`"dependencies": {
    "vue": "^2.1.10",
    "vue-router": "^2.2.0",
    "vuex": "^2.1.2"
  },`
src/vuex/index.js
`import Vue from 'vue'
import Vuex from 'vuex'
console.log(Vuex)//undefined
Vue.use(Vuex)
const  state = {
  count: 0
}
export default new Vuex.Store({
  state
})
`
src/main.js
`import Vue from 'vue'
import App from './App'
import router from './router'
import store from './vuex'
new Vue({
  el: '#app',
  router,
  store,
  template: '<App/>',
  components: { App }
})`
/*
Uncaught TypeError: Cannot read property 'installed' of undefined
Vue.use	@	vue.common.js?c3c9:3443
*/
I think I have correctly installed vuex, but vuex is undefined.

**Comment by ktsn** [comment]
Please make sure to follow [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) - the version of Vue and Vuex that you are using, step to reproduce the  problem and reproduction by jsfidde or codepen etc. are needed. If it is difficult to make reproduction, providing github repository that reproduce the issue is also ok.
Thanks.

**Comment by shuang6** [comment]
I have solved the problem after I renamed "src/vuex/index.js" to "src/vuex/store.js". It seems that I can't use "index.js" as a name.
