### ISSUE TITLE
How to empty/cleanup/overwrite the state inside module mutation?

### ISSUE THREAD

**Issue by ruslankonev** [vuejs/vuex#638]
Hello, I need to cleanup the user module store in my logout action/mutation.

In login action I get the user info and store it into the user state. After logout action/mutation I want to empty the state, but I can't — the local user state was update, but in global store the state is not mutate. How I can set after logout initial (base) state?

```
let state = {
  trackSettings: [],
  tradings: [],
  _token: null
}
```

**Comment by ktsn** [comment]
Thank you for filing this issue. However your issue seems a usage/support question.
Please make sure to follow [Issue Reporting Guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) when opening an issue. The issue list is exclusively reserved for bug reports and feature requests. Questions should be posted on [forum](https://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or StackOverflow.
Thanks.
