### ISSUE TITLE
mapActions does not ready when beforeCreate runs

### ISSUE THREAD

**Issue by DQvsRA** [vuejs/vuex#646]
I found strange behaviour, methods from ...mapActions does not initiated when beforeCreate runs. And on created() it will works. Is this a normal?

![screenshot from 2017-02-21 00 37 35](https://cloud.githubusercontent.com/assets/442111/23145440/5d87a468-f7ce-11e6-91f4-e12f3192bc71.png)

**Comment by yyx990803** [comment]
This is expected behavior.

**Comment by DQvsRA** [comment]
But why? I suppose it would be better to have all methods ready at the time when "beforeCreate" called.

**Comment by ktsn** [comment]
`beforeCreate` means the time before creating vm assets such as `data`, `computed`, `props`, `methods` and so on. If you would like to use such things in lifecycle callback, you should use `created`.

**Comment by DQvsRA** [comment]
Ok, it's clear, i'm already using `created`. 
But what is the use case of `beforeCreate`, since we moved all business logic to vuex store?

**Comment by ktsn** [comment]
Some plugins requires initialization before creating vm, like Vuex's `$store` or Vue Router's `$route`. So that, for example, you can use them in `data` options and make initial data depends on them.
I encourage you to use [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue) if you have further questions. Thanks.
