### ISSUE TITLE
弄了一早上了，没头绪。TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by psychokiller666** [vuejs/vuex#647]
有一个问题vue2.0的问题困扰一早上了，就是在vuex的mutations里，操作删除state里的数据

用Vue.delete 这个方法的时候报错

![image](https://cloud.githubusercontent.com/assets/15126424/23154784/930f0d3e-f84a-11e6-86fb-a688de278011.png)
![image](https://cloud.githubusercontent.com/assets/15126424/23154788/9608fbd0-f84a-11e6-984d-d58bb8c2ec3f.png)

**Comment by psychokiller666** [comment]
vue和vuex版本
"vue": "^2.1.10",
"vuex": "^2.1.2",

**Comment by crossjs** [comment]
items 应该是 object，而不是 array

https://cn.vuejs.org/v2/api/#Vue-delete

**Comment by ktsn** [comment]
Please make sure to follow the [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) when opening an issue. 
In particular, minimum live reproduction by jsfiddle or codepen is needed to solve the problem. If you cannot reproduce the problem on online playground, you can create the example project on github repository.

**Comment by limichange** [comment]
最好使用uuid或key做标识来删除。
```js
state.list.items = state.list.items.filter(item => item.uuid === uuid)
```

**Comment by CodinCat** [comment]
`Vue.delete()` can delete items of an array without any error, but it doesn't make sense. And according to the error message I don't think the problem is `Vue.delete()`.

Also this is not an issue but a question. You should ask on [forum](https://forum.vuejs.org/) or stackoverflow. I think this issue can be closed now.
