### ISSUE TITLE
npm install出现错误，不明

### ISSUE THREAD

**Issue by files3** [vuejs/vuex#653]
![wechatimg1](https://cloud.githubusercontent.com/assets/15240870/23244000/8184b20c-f9bd-11e6-911a-19c9b4f407cd.jpeg)

是我node版本的问题吗？

**Comment by ktsn** [comment]
Please make sure to follow the [issue reporting guideline](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) when opening an issue. 
In particular, minimum reproduction is needed to solve the problem. Could you share the example project on github repository so that we can take a look this problem?

**Comment by files3** [comment]
我先找一找这个问题

**Comment by limichange** [comment]
安装chromedriver这个包必须翻墙，不然会报错。

**Comment by fnlctrl** [comment]
Closing as the issue is resolved.

English version of this issue: `chromedriver` cannot be normally installed in China because the resource has been blocked by GFW.
