### ISSUE TITLE
How to log all actions on store?

### ISSUE THREAD

**Issue by iabdulin** [vuejs/vuex#670]
Is it possible to log actions the same way I can log mutations with plugins?

I have a simple custom plugin to log mutations:
```coffeescript
new Vuex.Store
  plugins: [( (store) ->
      store.subscribe (mutation, state) ->
        console.log mutation.type, mutation.payload
    )]
```

I wonder how can I log all actions called with `store.dispatch`

**Comment by LinusBorg** [comment]
Hello @iabdulin 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.

**Comment by ericmuyser** [comment]
> reserved exclusively for bug reports and feature requests

I'd like to request this feature ;)

**Comment by LinusBorg** [comment]
You can do that for quite some time now, we have store.subscribeAction() for that.
