### ISSUE TITLE
In the component instance into the store, sub-components are not accessible

### ISSUE THREAD

**Issue by cytGitHub** [vuejs/vuex#697]
```
new Vue({
	el:"#app",
	router:router,
	store:store,
	render:h=>h(AppComponent)
});

import store from './store/store.js';


import Vue from 'Vue';
import Vuex from 'Vuex';

Vue.use(Vuex);
export default new Vuex.Store({
	// state,
	// actions,
	// mutations
	state:{
		count:0,
		num:0,
		name:"smith",
		age:20
	},
	mutations:{
		increment(state){
			state.count++
		},
		decrement(state){
			state.count--
		}
	},
	action:{
		increment:({commit}) => commit('icrement'),
		decrement:({commit}) => commit('decreament')
	}
})
```
Then in my subcomponent, visit this. $ Store = undefined ？ why ~ And the console is ok~

**Comment by LinusBorg** [comment]
Hello @cytGitHub 

Thank your for your interest in this project.

However, your issue is a usage/support question, and the issue tracker is reserved exclusively for bug reports and feature requests (as outlined in our [Contributing Guide](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)).

We encourage you to ask it on the [forum ](http://forum.vuejs.org) , [Stack Overflow](http://stackoverflow.com/questions/tagged/vue.js) or on [gitter](http://gitter.im/vuejs/vue) and are happy to help you out there.
