### ISSUE TITLE
On accessing getters from store its undefinied but in debugger its available

### ISSUE THREAD

**Issue by Ahrimaan** [vuejs/vuex#825]
### Version
2.3.0

### Reproduction link
[https://github.com/Ahrimaan/MettAppVue](https://github.com/Ahrimaan/MettAppVue)

### Steps to reproduce
I have a store where Authenticationinfo is stored.
When i try to access the store getters from the Login-Component it throws a undefinied error. 
When i debug it in Chrome, i can access all getters in the console window, but the code throws an error anyway

See here: https://abload.de/img/vuex.error0puo1.jpg

### What is expected?
getters throw no error

### What is actually happening?
getters throw error

**Comment by LinusBorg** [comment]
1. This likely a configuration problem, not a bug.
2. I can't verify because you did not provide a minimal reproduction, you provided a whole projet with vue-router and many other things probably unrelated to the problem.

Please ask for help on our forum.vuejs.org and open an issue when you are sure to have found a bug.

**Comment by LinusBorg** [comment]
On second look: you use an arrow function for mounted, which you shouldn't (as explained in your documentation)
