### ISSUE TITLE
dispatch errors should return a rejected promise and not undefined

### ISSUE THREAD

**Issue by TomKaltz** [vuejs/vuex#850]
### What problem does this feature solve?
When calling store.dispatch('nonExistentAction') the function returns with undefined.  Should this instead return a rejected promise with the error?

### What does the proposed API look like?
```
store.dispatch('nonExistentAction')
  .then((result)=>{ ... })
  .catch((e)=>{ ... })
```
If the action does not exist the catch handler will be called with an aptly named error.

**Comment by LinusBorg** [comment]
Well, if you return a Promise from the action that rejects with an error, then you can atch it in the component:

https://jsfiddle.net/ztfL4Lav/1/

So I don't understand what you propose, sorry. Am I missing something?

**Comment by ktsn** [comment]
I don't think we should treat the non-existent action error as same as the normal action errors because they are different kind of errors - The former is developers' mistake that should not be handled in application code while the latter is application error that can be handled.

@LinusBorg 
He suggests that `dispatch` should return a Promise that has an error object if there are no registered action in Vuex.

**Comment by LinusBorg** [comment]
Oh! Totally misunderstood, thanks for setting me straight ^^

**Comment by TomKaltz** [comment]
https://github.com/vuejs/vuex/blob/dev/src/store.js#L120
Undefined return. Wondering if this should just Promise.reject(...)

**Comment by ktsn** [comment]
If it returns Promise in that case, that implies Vuex allows the users handle the non-existent action error in application code. As I described above, it shouldn't be handled in application code.
IMO, it shouldn't return any value because there seems to be no valid use case to return Promise and it is the case that the warning will be provided. It's like an assertion error.

**Comment by TomKaltz** [comment]
I use this in a server-side plugin.  It's a task queue that fires actions requested by remote endpoints.  My plugin may try to fire non-existent actions.  No problem.  I will handle the undefined return in my plugin code.
