### ISSUE TITLE
热更新不工作

### ISSUE THREAD

**Issue by MorisHarA** [vuejs/vuex#856]
### Version
2.3.0

### Reproduction link
[https://jsfiddle.net/0k2e8ded/](https://jsfiddle.net/0k2e8ded/)

### Steps to reproduce
vue-cli 生成的项目，配置store不能热更新，module.hot.accept不回调

### What is expected?
不知道哪里出了问题

### What is actually happening?
无法是用热更新

**Comment by ktsn** [comment]
This is not a valid reproduction because we cannot run the code in our machine.
Please provide self-contained reproduction as a github repository.

**Comment by MorisHarA** [comment]
https://github.com/MorisHarA/app

**Comment by MorisHarA** [comment]
@ktsn

**Comment by ktsn** [comment]
This is likely because your webpack config problem rather than Vuex since page reload is triggered when the module is updated.
Also we encourage you to use our [forum](https://forum.vuejs.org) or [chat room](https://vue-land.surge.sh/) when you ask your questions since the issue list is reserved for bug reports and feature requests.
Thanks!
