### ISSUE TITLE
Option to not connect to dev tools

### ISSUE THREAD

**Issue by Austio** [vuejs/vuex#875]
### What problem does this feature solve?
Hello, I would like to create a pull request that would allow an option to be passed to Vuex constructor to have it not connect to dev tools.  Useful in production so it doesn't connect to __VUE_DEVTOOLS_GLOBAL_HOOK__

This would reduce ease of someone being able to access the store from client.

### What does the proposed API look like?
Proposed API would be something like

```
const store = new Vuex.Store({ 
  connectToDevTools: Bool 
})
```

By default I would default connectToDevTools to true.

**Comment by posva** [comment]
devtools are already hidden in production mode. Why would you need something like this?

**Comment by Austio** [comment]
Hmmm, totally possible i'm missing something in my config, but it looks like in production Vue is not connecting but the store is to window.__VUE_DEVTOOLS_GLOBAL_HOOK__

Notice the Vue is null but store has a reference

![image](https://user-images.githubusercontent.com/1709860/28423509-dd617e98-6d30-11e7-9a13-6f185ce82375.png)

I checked a few other sites that are using vue (like vuejs jobs) and they have this hook.  So long as that thing is present I think the boot will always add it. 

Relevent Plugin: https://github.com/vuejs/vuex/blob/2a67103a1f5fc1448a694e7f83a5f0c6d6bc8262/src/plugins/devtool.js

Line that loads it:
https://github.com/vuejs/vuex/blob/67da6225552e46266ed059c7f0d0128294cd08ed/src/store.js#L61

**Comment by LinusBorg** [comment]
Hm yeah, we could probably not load the plugin if `Vue.config.devtools = false`.

However since the devtools won't show during productiuon anyway, that's more for possible performance-implication than anything else...

**Comment by ktsn** [comment]
Well, I'm not sure why we need to have this config in Vuex side as well. I think there are only cases that it's both enabled (in development) or both disabled (in production).

If you mean that you would like to avoid devtool initialization, it would be better to use `Vue.config.devtools` rather than a new option.

**Comment by LinusBorg** [comment]
@ktsn Yeah, but the point is that currently, no matter what `Vue.config.devtools` is set to, vuex will emit `vuex:init` to the devtools.

If that doesn't do anything in devtools because the devtools didn't receive an initial `init` event, then we don't have an issue. If `vuex:init` does do something, we should simply do:

```javascript
import Vue from 'vue'
if (Vue.config.devtools) {
  // apply plugins
  plugins.concat(devtoolPlugin).forEach(plugin => plugin(this))
}
```

**Comment by ktsn** [comment]
@LinusBorg Yeah, I actually think about that. I'll work on it later.

**Comment by Austio** [comment]
@ktsn would you accept a PR to configure this using a flag option similar to

```
const store = new Vuex.Store({ 
  connectToDevTools: Bool 
})```

Seeing this configuration being beneficial in another scenario where we have two separate Vuex instances on the same app and we would like to tell one of them to not connect to devtools.
