### ISSUE TITLE
Will be good to have possibility to switch off strict mode for specified modules

### ISSUE THREAD

**Issue by ArtemConstntinov** [vuejs/vuex#917]
### What problem does this feature solve?
In the case when as a state object need to be an encapsulated class with own inner states what is not related to the base app and it needs to be partial mutated by VUEX, for making that work:` { strict: false }` . But it's not a good idea for development when participating an extended team coz that control needs to be set at other VUEX modules that don't use the encapsulated class to store it in the state.

### What does the proposed API look like?
```
class MyClass {
   ...
}

const module1 = {
namespace: true,
strict: false,  
state: {
      someState: new MyClass()
    }
.
.
.
}

const module2 = {
namespace: true,
strict: false,  
state: {
      someState: null
    },
.
.
.
}

const module3 = {
namespace: true,
state: {
      someState: null
    },
.
.
.
}

export default new Vuex.Store({
  modules: {
   module1,
   module2,
   module3
  },
  strict: true
})
```

**Comment by ktsn** [comment]
Why would you construct your app in such structure?
It should be always avoided to mutate the state out of mutations. If you would like to integrate existing apps with Vuex store, I think you should create adapter module as a plugin that synchronize the existing apps state and Vuex state.
In addition, managing strict mode for each module would be quite extensive.

**Comment by ArtemConstntinov** [comment]
True, can be realized via plugins, only one minus of that can not use getters  for retrieve encapsulate app status, instead, need to call mutation for update status parameter to Vuex store and only after can get it

**Comment by mnussbaumer** [comment]
@ktsn actually that may make sense in some situations, but not in all situations. In fact, given that `strict` is turned off in production (or advised to be so) it seems it's a tool for development to pinpoint and limit mutations (so that you don't mutate state from where you shouldn't and construct your app correctly), which is useful, but if say, I add a socket lib, that creates a socket object, and I want to set that socket object in a module inside vuex, it would make pretty much sense to allow it to mutate itself outside of vuex - for that module only - since it's probably way easier to allow the library to manipulate that object than me re-writing its api as a vuex plugin don't you think? Because here I'm pretty much aware of the trade-off between "pseudo enforcing" strictness and allowing this one module to be mutated on other rules. I can just turn off strict globally, but then if at some point I mistakenly make a mutation outside of a mutation handler I won't be warned - and if I'm working with a team then it becomes worse - whereas if I can turn it off for a module, I only need to pay attention to not screwing that one.

Just my opinion having run into this right now

**Comment by kticka** [comment]
Same here. It's okay if you have small SPA or something like that, where you can write everything in "vuex way". But if you want to use vuex just as a part of bigger application, where objects have their own cache mechanisms and so on, you will get tons of errors without ability to exclude those modules from strict mode.
