### ISSUE TITLE
Getters are editable when using arrays

### ISSUE THREAD

**Issue by faylite** [vuejs/vuex#923]
### Version
2.4.0

### Reproduction link
[https://jsfiddle.net/j2kf99x5/](https://jsfiddle.net/j2kf99x5/)

### Steps to reproduce
* Setup vuex store
* Create a getter that returns a array of object
* `$store.getters.getSomeArray[0].name = "this should work but it does"`

### What is expected?
I expect it to not enable editing of the state directly

### What is actually happening?
State is edited directly resulting in my data transformers overwriting the state and break the entire data integrity

**Comment by LinusBorg** [comment]
vuex state is *not* immutable, so this is expected behaviour, and not for arrays either, but objects as well.

The recommended approach is to turn on [strict mode](https://vuex.vuejs.org/en/strict.html) during develpoment / testing to catch situations where you would accidentally mutate the state outside of a vuex mutation.
