### ISSUE TITLE
is it possible to use object setters to track changes of the global state, instead of calling  dispatch/mutations?

### ISSUE THREAD

**Issue by beeplin** [vuejs/vuex#93]
very glad to see the new api decouples actions from store and makes us able to freely write actions directly inside components (of coz we can still write shared actions in a cross-component place and import them into components). This virtually makes us able to call store.dispatch anywhere.

So is it possible to decouple mutation/dispatch from vuex, too?

I like the philosophy of flux very much, but i am nerver a fan of redux api. Flux/redux uses this state-muations-actions-like api mainly because it's designed for general frameworks like react that don't have built-in 'reactive tracking' feature. So it has to call dispatchers explicitly to trigger the re-computation of the state properties. 

but in vuex things are different. this mutation/dispatch approach borrowed from flux wastes some cherished features of vue. vue has built-in 'reactive tracking' feature by tweaking getters/setters of its reactive objects. so i guess maybe in future we can also allow users to freely call `state.xxx = yyy` anywhere in their components, no need to writing piles of mutations in certain other places outside their components. by tweaking setters of the state, vuex would be able to watch and track such modifications of state and log them by debug middlewares. this would make our code more concise and straightforward, and at the same time can still keep the application well structured and benefit from the powerful debug potential of vuex.

i know this would lose the info of the string name of mutations in the current design, which might make the debug log somehow difficult to read, but anyway the time-travel feature would still be available for basic debugging. 

if there is no technical difficulties preventing us to do so, it might be attracting to at least provide an option in the future versions of vuex that enable this kind of 'non-dispatch' writing to the state.  how do you guys think of this? pls point out if i am wrong. :)

**Comment by yyx990803** [comment]
It should be noted that these patterns are not only for being able to "track", but also to provide structure to your code so that **you know what type of code belongs where**. For example, in a current Vuex app, you know that code that changes state can only happen inside mutations - you don't have to guess where it happened.

This is a conscious tradeoff between "convenience" and longer term maintainability, which is also why I don't recommend using it for simple projects. However if you are indeed building a large app, then you will likely appreciate these restrictions when your codebase grows and more people start working on it.
