### ISSUE TITLE
Copying the state for local component mutations

### ISSUE THREAD

**Issue by TeemuKoivisto** [vuejs/vuex#996]
### What problem does this feature solve?
Hi. I recently ran into a following problem:

I have getter that returns a slice of state that is an array:  
`answers: state => state.answers`

Then I use that getter inside my component and pass the computed value down to a child component using v-model:  
`v-model="answers[getAnswerIndex(question.id)]"`

Problem arises when v-model modifies that property doing so also modifying it inside state(?). I tried to negate the problem by using a copy of the array:  
`this.answersCopy = JSON.parse(JSON.stringify(this.answers))`

But this again causes v-model not to work as answersCopy is no longer observable. (And also it looks hackish). Other copying methods didn't work as they either weren't observable anymore or the observable id remained the same (thus changing also the state).

I think current documentation leaves too much open for the developer to interpret and copying the state should be better documented/more obvious to the developer. I mean just by allowing me to change state directly was a big wtf-moment. I'd rather have the getters return read-only values and only by directly copying it inside eg. created()-hook in a specific way you could unlock the setter for that particular copy. Two-way data binding is always a bit messy but that would at least make it implicit that you know that you're changing this particular copy of state.

### What does the proposed API look like?
Vuex getters return read-only values by default. Only by using something like:  
`this.itemsCopy = Vuex.mutableCopy(this.items)`

You could create mutable versions of the said computed properties. Or the Vuex observables can be mutated but it does not affect the state in any way. But that would make it a bit too ambiguous in my mind.

**Comment by TeemuKoivisto** [comment]
Okey I figured out why the observable wasn't working, I didn't declare the variable in the data() -block. Doing that and copying it with `this.answersCopy = this.answers.map(a => a)` solved the problem.

But my point still stands, I can not imagine a situation in which I would want to mutate state directly. Sure implementation-wise scoping the modifications only happen inside mutations block might not be a trivial task.

**Comment by LinusBorg** [comment]
> I can not imagine a situation in which I would want to mutate state directly

Then simply don't use `v-model`, use `v-bind:value` and `v-on:input` instead.

**Comment by mkpaz** [comment]
I'm really don't understand. [Here ](https://forum.vuejs.org/t/vuex-form-best-practices/20084/2) is a forum topic where was said that one can mutate state directly. It's just a matter of "functionality that you want for your users". If so then why I need mutations at all? It's basically just setters.

But let's [look at the doc](https://vuex.vuejs.org/en/mutations.html), it states "The only way to actually change state in a Vuex store is by committing a mutation". Actucally there are abundance of contradicting answers which is very confusing. I agree with @TeemuKoivisto, if state supposed to be immutable, please provide something like `Vue.createMutableAndObservableCopyAndBeSureThatIsCorrectApproach()`.

**Comment by LinusBorg** [comment]
> where was said that one can mutate state directly.

That post is by me, and I don't say to mutate state directly anywhere in that post. Please point me to the sentence or praragraph that makes you think that.

* One of the two approaches changes the state by committing a mutation
* The other edits a *local*(!) copy of the object (not the store state!), and then commits the final result at the end, with a mutation.

Nowhere is store state mutated outside of a mutation.

**Comment by mkpaz** [comment]
@LinusBorg I'm very sorry. Official doc gives [only one trivial example ](https://vuex.vuejs.org/en/forms.html)that doesn't fit in most cases. Just spent a half of the day digging SO, Github and Vue forum to find out how to mutate vuex state properly.  It's messing with my head so I didn't notice mutation in the first appoach.

> Oh, so maybe you misunderstand the recommendation to never mutate state outside of a mutation to mean that vuex enforces this by creating immutable objects? That's not the case.
> 
> You seem to understand "the only way [...] is" to mean "the only way that technically works", when in reality it means "the only way allowed by the pattern, which you can enforce in development by using strict mode".

Yeah, for me "only way" sounds like "single way", pretty imperative, certainly not like recomendation. It should be "the only conventional way", kind of.

**Comment by LinusBorg** [comment]
Understandable - but I think reading the page about strict mode makes it quite clear that vuex state *can* be mutated outside of the store, but shoudln't - which is why "strcit mode" exists for development:

https://vuex.vuejs.org/en/strict.html

**Comment by luisjoserivera** [comment]
Hi. Just like to point out a total beginner perspective. I just started learning Vue and Vuex altogether (getting into the reactive world) and I agree with the point being discussed here of the way docs and articles are stating "recommendations" (like "the only way to change state..."). To me (and let me repeat, I'm a novice) that kind of statements don't sound like a recommendation at all.

I was totally confuse when a computed prop inside component X sorted an array returned from a store getter and in component Y the values of the getter reflected a mutation. I've been looking around in my code and googling for hours trying to catch what bug was letting me do something that from my understanding of what I've read "was not doable".

We could keep arguing about what is a recommendation and what is not, but lets be real... The first paragraph in the docs > What is Vuex? says "Vuex is a state management pattern + library for Vue.js applications. It serves as a centralized store for all the components in an application, **with rules ensuring that the state can only be mutated in a predictable fashion**"

So, I wonder... is it a rule or is it an option? And if it's a rule why I'm able to violate it?

If we are able to violate the rules the whole "predictable fashion" philosophy in which Vuex is based starts to sound just like marketing and Vuex ends up being just another opinionated utility, doomed to failure just because it can't even ensure its main selling feature, which is "a predictable state management environment".

**Comment by nccurry** [comment]
I am still confused on the correct data flow when a component neds to read and write to the same object in the vuex store.

Am I supposed to copy the state data returned from a getter into the components local data and use that local copy when dispatching actions? Where is that copy supposed to occur? In the compunents mounted() lifecycle hook? In updated()? Somewhere else?

**Comment by nccurry** [comment]
Understanding the difference between using v-model and :value/@on alleviated this issue for me.

If you are going to put data from vuex directly into a component do not use v-model as that will write changes to the vuex store data automatically. Use v-bind:value and v-on:input manually instead to control what happens when something changes.

https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
https://stackoverflow.com/questions/42260233/vue-js-difference-between-v-model-and-v-bind

```
From here - Remember:

<input v-model="something">

is just syntactic sugar for:

<input
   v-bind:value="something"
   v-on:input="something = $event.target.value"
>

or (shorthand syntax):

<input
   :value="something"
   @input="something = $event.target.value"
>```

**Comment by kiaking** [comment]
I think we can close this issue now, since it's more about questions rather than an issue. Please feel free to open another issue if there's anything! 👍
